// ============================================================================
//  A REAL v1 SAVE, FROZEN AS BYTES.
//
//  *** NEVER REGENERATE THIS FILE. Regenerating it is the one thing that ***
//  *** destroys its value. A fixture regenerated by the build that broke  ***
//  *** it proves nothing: it will agree with whatever the reader does     ***
//  *** today, which is precisely the question it exists to answer.        ***
//
//  If a test against this fixture goes red, the answer is a migration, or a
//  bug fix, or a deliberate `MIN_SUPPORTED_SCHEMA_VERSION` bump signed off by
//  a human. The answer is never "re-run the generator".
// ============================================================================
//
// Why this exists at all. Every other test in the suite reads what it just wrote:
// `deserialise(serialise(world))`. That proves the reader is the inverse of the
// writer IN THIS BUILD, and nothing more — rename a key in both directions and the
// whole suite stays green while every save file on disk becomes unreadable. These
// bytes were written once and are never written again, so from now on the reader
// must keep accepting THIS text and producing THIS hash.
//
// It is also the stored v1 blob that `PARKING.md` asked for at bootstrap, so the
// first genuine schema bump has real old data to migrate rather than a synthesised
// one. That has a deliberate consequence, signed off at PLAN: the next field added
// to `World` makes this an old-shaped save, `assertWorldShape` rejects it, and the
// change owes a real v1 -> v2 migration. That is the point. Today a new field
// silently changes what every existing save means; after this it fails loudly
// against committed bytes and forces a deliberate schema decision.
//
// Generated once on 2026-08-07 by a throwaway script against commit 8f1b7ff, from a
// 5,000-tick run under `SAVE_V1_CONTENT`: seed 4242, four spawns, two despawns, two
// ledger entries. Kinds are camelCase because a snake_case literal in packages/sim
// is a leaked content ID (ADR-0003).

import type { SimContent } from '../content.js';

/**
 * The exact content this world was created under.
 *
 * Frozen here alongside the bytes, deliberately NOT the shipped content in
 * `packages/content`: a save is only loadable under the content it was made with
 * (G-002), so pointing this at production content would make an innocent price edit
 * turn `test:save` red for a reason that has nothing to do with I6.
 */
export const SAVE_V1_CONTENT: SimContent = Object.freeze({
  roomTypes: Object.freeze([
    Object.freeze({ id: 'fixtureRoom', name: 'Fixture Room', capacity: 2, nightlyRatePence: 8_500 }),
    Object.freeze({ id: 'fixtureSuite', name: 'Fixture Suite', capacity: 4, nightlyRatePence: 19_900 }),
  ]),
});

/**
 * The save file, byte for byte, as `serialise` produced it.
 *
 * A single-quoted string, so the JSON's own double quotes need no escaping and what
 * is in this source IS what was on disk. It is not a `.json` file because
 * `packages/sim/tsconfig.json` sets `types: []` — there is no `@types/node`, so a sim
 * test cannot read a file — and importing JSON yields a parsed object rather than the
 * bytes, which is the thing under test.
 */
export const SAVE_V1_BYTES =
  '{"schemaVersion":1,"world":{"tick":5000,"rng":{"a":380611476,"b":3528236117,"c":3141763490,"d":24321242},"ledger":[{"tick":1440,"amount":8500,"reason":"nightly revenue"},{"tick":2880,"amount":-2500,"reason":"nightly upkeep"}],"entities":{"nextId":6,"list":[{"id":2,"kind":"fixtureSuite"},{"id":4,"kind":"fixtureSuite"},{"id":5,"kind":"fixtureRoom"}]},"contentHash":"8e09fe4f0fa162a3"}}';

/** `hashState` of the world those bytes encode. Pinned as a literal on purpose. */
export const SAVE_V1_STATE_HASH = '7880a56adc457726';

/** `bindContent(SAVE_V1_CONTENT).fingerprint`, as recorded in the blob. */
export const SAVE_V1_CONTENT_FINGERPRINT = '8e09fe4f0fa162a3';

/** The tick the save was taken at. */
export const SAVE_V1_TICK = 5_000;
