// G-014b — THE WHOLE RUN REPORT FROM THE ERA BEFORE THE HYSTERESIS MARGIN EXISTED.
//
//   node --import tsx tools/headless/src/cli.ts \
//     --days 30 --seed 7 --rooms 6 --arrivals 60 --amenities 2 --json
//
//   run against commit 627a1f4, working tree CLEAN, the last build in which a guest could
//   not abandon an engagement at all. These are the bytes that process wrote.
//
// *** NEVER REGENERATE THIS. *** It describes an era that is over, so it is a frozen
// literal (ADR-0008 (2)). A fixture regenerated by the build that changed the behaviour it
// describes agrees with whatever the writer now does, which is the exact property it exists
// to deny — `fixtures/summary-v1.ts`'s argument, one document over.
//
// ============================================================================
//  WHY THE WHOLE DOCUMENT AND NOT THE NEED COUNTERS (`ai-critic`, MINOR 3).
//
//  Criterion 3's `margin 10000` arm is the strongest reservation-leak detector in this
//  goal, and the leak it detects is INVISIBLE in the need table. An implementation that
//  speculatively `held.add`s a challenger it then declines to switch to leaves a guest
//  holding two providers; that surfaces as `orphanedReservations`, `stuck` and `inHotel`,
//  and moves no `met` or `unmet` anywhere. Pinning only the need rows would have made this
//  arm blind to the failure mode it is best placed to see.
//
//  So the comparison is against every field of the document, and the ONE permitted
//  difference is stated rather than assumed: `world.stateHash`, which must differ, because
//  the shipped content now carries a fifth table and `World.contentHash` is hashed state.
//  Same behaviour, different content document — both halves asserted.
// ============================================================================
//
// WHAT THIS ERA IS. `guest-rules.json` did not exist, so `reserve` returned early for any
// engaged guest. That is reproducible from disk today at `abandonMarginBasisPoints: 10000`:
// a pending need's pressure cannot reach one whole (`MAX_PENDING_PRESSURE_BASIS_POINTS`,
// tied to `isNeedPending`'s own definition), and a challenger must EXCEED the incumbent by
// the margin — so the comparison can never succeed. Total commitment is a CONTENT
// DOCUMENT, not a dead code path, which is what makes this arm runnable at all.

/** The document, exactly as the pre-margin CLI wrote it, whitespace removed. */
export const ERA_A_TOTAL_COMMITMENT = Object.freeze(
  JSON.parse(
    '{"schema":2,"input":{"seed":7,"ticks":43200,"rooms":6,"amenities":2,"arrivalEveryTicks":60,' +
      '"buildEveryTicks":0,"demolishEveryTicks":0,"loanEveryTicks":0},"world":{"tick":43200,"days":30,' +
      '"roomTypes":4,"needTypes":4,"entities":22,"stateHash":"a4e48aa33e96b117"},"guests":{"arrived":720,' +
      '"departures":[{"reason":"satisfied","count":534},{"reason":"gaveUpWaiting","count":177},' +
      '{"reason":"evictedRoomGone","count":0},{"reason":"evictedRoomUnusable","count":0},' +
      '{"reason":"evictedCauseUnrecorded","count":0}],"inHotel":9,"stuck":0,"orphanedReservations":0,' +
      '"inInvalidRooms":0},"needs":[{"needId":"guest_comfort","lodging":false,"met":474,"unmet":237,' +
      '"metByItem":474},{"needId":"guest_entertainment","lodging":false,"met":415,"unmet":296,"metByItem":0},' +
      '{"needId":"guest_nourishment","lodging":false,"met":534,"unmet":177,"metByItem":178},' +
      '{"needId":"night_rest","lodging":true,"met":534,"unmet":177,"metByItem":0}],"rooms":{"valid":12,' +
      '"invalid":{"missingItem":0,"noDoor":0,"unplaced":0,"unsupported":0}},"money":{"transactions":565,' +
      '"revenuePennies":4539000,"upkeepPennies":-720000,"constructionPennies":0,' +
      '"startingCapitalPennies":500000,"demolitionRefundPennies":0,"loanDrawPennies":0,"loanFeePennies":0,' +
      '"loanRepaymentPennies":0,"liquidationValuePennies":1500000,"outstandingDebtPennies":0,' +
      '"settlements":30,"nights":30,"balancePennies":4319000},"build":{"built":0,"demolished":0,' +
      '"refused":{"insufficientFunds":0,"noSuchRoom":0,"occupied":0,"outOfBounds":0},' +
      '"constructionTransactions":0,"refundTransactions":0},"loans":{"drawn":0,' +
      '"refused":{"noLoanOffered":0,"notEligible":0},"drawTransactions":0}}',
  ) as Record<string, unknown>,
);

/**
 * The invocation those bytes came from, as the CLI takes it. Read by the test rather than
 * retyped, so the fixture and the arm that reproduces it cannot describe different hotels.
 */
export const ERA_A_INVOCATION: readonly string[] = Object.freeze([
  '--days',
  '30',
  '--seed',
  '7',
  '--rooms',
  '6',
  '--arrivals',
  '60',
  '--amenities',
  '2',
]);

/** The commit those bytes were taken at, so the claim above can be re-run. */
export const ERA_A_REVISION = '627a1f4';

/**
 * The one field of the document that is ALLOWED to differ when the era is reproduced from
 * content, and the reason it must.
 *
 * `World.contentHash` is hashed state, and the shipped content now carries a fifth table
 * (`guest-rules.json`), so every state hash under it moved whether or not any guest behaves
 * differently. A test that let the whole document differ would prove nothing; one that
 * required the hash to MATCH would be asserting that adding content does not change the
 * content fingerprint, which is false and would be a defect if it were true.
 */
export const ERA_A_EXPECTED_DIFFERENCE = 'world.stateHash';

/**
 * The key `RunSummary.needs` gained at G-014b, absent from every row above.
 *
 * Named here so the era comparison can say "every field this document has, plus exactly
 * this one, at zero" rather than hand-listing the fields it does compare — a list that
 * would silently stop covering a field the next goal adds.
 */
export const NEED_KEY_ADDED_AT_G014B = 'abandoned';
