// A REAL SUMMARY SCHEMA 1 DOCUMENT, CAPTURED BEFORE G-015 CHANGED THE SHAPE.
//
//   node --import tsx tools/headless/src/cli.ts --days 2 --seed 42 --json
//
// run against commit a011f38 (G-014a), the last build that emitted schema 1. These are the
// bytes that process wrote, with only the whitespace removed.
//
// *** NEVER REGENERATE THIS. *** It describes an era that is over, so it is a frozen
// literal (ADR-0008 (2)). A fixture regenerated by the build that broke it agrees with
// whatever the writer currently does, which is the exact property it exists to deny — the
// argument ADR-0006 makes for `fixtures/save-v1.ts`, applied one document over.
//
// WHAT IT IS FOR, AND IT IS ONE THING: proving that `assertSummarySchema` ACCEPTS a real
// v1 document and REFUSES a v2 one. A guard that has only ever been handed the version it
// wants is not a guard (ADR-0007), and a guard tested against a v1 document this build
// synthesised would be testing the synthesiser.
//
// IT IS NOT A GOLDEN AND NOTHING COMPARES A CURRENT RUN TO IT. `cli.stdout.test.ts` owns
// the golden for the current schema and moved to v2 with everything else. Note in passing
// that the two agree where they overlap — 24 arrived, 15 satisfied, 5 unsatisfied — which
// is what makes the migration of that golden a reshape rather than a rewrite.

/** The document, exactly as the schema-1 CLI wrote it. */
export const SUMMARY_V1_DOCUMENT = Object.freeze(
  JSON.parse(
    '{"schema":1,"input":{"seed":42,"ticks":2880,"rooms":3,"amenities":1,"arrivalEveryTicks":120,' +
      '"buildEveryTicks":0,"demolishEveryTicks":0,"loanEveryTicks":0},"world":{"tick":2880,"days":2,' +
      '"roomTypes":4,"needTypes":4,"entities":11,"stateHash":"e6a114d0e41934fc"},"guests":{"arrived":24,' +
      '"satisfied":15,"unsatisfied":5,"evicted":0,"inHotel":4,"stuck":0,"orphanedReservations":0,' +
      '"inInvalidRooms":0},"needs":[{"needId":"guest_comfort","lodging":false,"met":11,"unmet":9,' +
      '"metByItem":11},{"needId":"guest_entertainment","lodging":false,"met":10,"unmet":10,"metByItem":0},' +
      '{"needId":"guest_nourishment","lodging":false,"met":15,"unmet":5,"metByItem":6},{"needId":"night_rest",' +
      '"lodging":true,"met":15,"unmet":5,"metByItem":0}],"rooms":{"valid":6,"invalid":{"missingItem":0,' +
      '"noDoor":0,"unplaced":0,"unsupported":0}},"money":{"transactions":18,"revenuePennies":127500,' +
      '"upkeepPennies":-24000,"constructionPennies":0,"startingCapitalPennies":500000,' +
      '"demolitionRefundPennies":0,"loanDrawPennies":0,"loanFeePennies":0,"loanRepaymentPennies":0,' +
      '"liquidationValuePennies":750000,"outstandingDebtPennies":0,"settlements":2,"nights":2,' +
      '"balancePennies":603500},"build":{"built":0,"demolished":0,"refused":{"insufficientFunds":0,' +
      '"noSuchRoom":0,"occupied":0,"outOfBounds":0},"constructionTransactions":0,"refundTransactions":0},' +
      '"loans":{"drawn":0,"refused":{"noLoanOffered":0,"notEligible":0},"drawTransactions":0}}',
  ) as Record<string, unknown>,
);

/**
 * The three keys schema 2 REMOVED, named here so a test can assert their absence.
 *
 * This list is the whole breaking change in one line, and the reason the version had to
 * move at all: `report.ts`'s policy exempts additions and does not exempt these.
 */
export const SUMMARY_V1_GUEST_KEYS_REMOVED_AT_V2 = Object.freeze([
  'satisfied',
  'unsatisfied',
  'evicted',
] as const);
