// G-013 — THE v6 -> v7 STEP, AND THE INVARIANT IT HAS TO SATISFY.
//
//   pnpm exec vitest run provider
//
// ADR-0006 fires for the SIXTH time. `World` gained two fields — `metBy` on every need and
// `metByItem` on every tally row — so the permanent v1 fixture is rejected again, the
// schema goes to 7, and the fixture walks 1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7. It is migrated,
// never regenerated: a fixture regenerated by the build that broke it agrees with whatever
// the writer currently does, which is the exact property it exists to deny.
//
// THIS FILE NO LONGER OWNS THE CURRENT ERA (G-015). It owned it until `World.guestOutcomes`
// became a table and the chain grew to v8; the current era is `outcome.save.test.ts`'s. Its
// claims about the v6 -> v7 step and its frozen literals are untouched by that — which is
// the whole point of ADR-0008 (2) — but the words "reaches" and "the chain" below now mean
// "runs through here", not "stops here".
//
// AND IT IS NOT TESTED BY THE FIXTURE, WHICH IS WHY THIS FILE EXISTS. The v1 fixture
// carries NO guests and NO tally rows, so v6 -> v7 would map over two empty arrays and
// report success having inspected nothing — ADR-0007's shape, in the one place this project
// has been bitten by it most often. Everything below drives a synthetic v6 world that has
// something to migrate.
//
// THE DEFAULTS ARE ARGUED FROM THE ERA, NOT CHOSEN (ADR-0008). A v6 world is one in which
// only ROOMS could provide anything, so every satisfaction recorded in those bytes WAS a
// room's: a met need becomes `metBy: 'room'` and every tally row gets `metByItem: 0`. Both
// are derived from the bytes (`progressRemaining === 0`) and from the era, never from
// content — so the same v6 bytes produce the same v7 world however the shipped table
// changes afterwards.
//
// Content ids here are camelCase (ADR-0003).

import { describe, expect, it } from 'vitest';
import { bindContent } from './content.js';
import type { NeedTypeData, RoomTypeData } from './content.js';
import { assertNeedVector, assertNeedOutcomes } from './needs.js';
import type { NeedOutcome, NeedState } from './needs.js';
import {
  deserialise,
  MIGRATIONS,
  MIN_SUPPORTED_SCHEMA_VERSION,
  SAVE_SCHEMA_VERSION,
  serialise,
} from './save.js';
import { createWorld, hashState } from './world.js';
import { stripDepth } from './without-depth.js';

const roomType = (id: string, provides: readonly string[]): RoomTypeData => ({
  id,
  name: id,
  capacity: 2,
  nightlyRatePence: 8_500,
  provides,
});
const need = (id: string, lodging: boolean): NeedTypeData => ({
  id,
  name: id,
  role: lodging ? 'lodging' : 'engagement',
  // G-027b: `capacityTicks` is time-to-empty, which is what `patienceTicks` named, so 100 is
  // carried; a refill is a whole tick, so 100/20 is 5 exactly.
  capacityTicks: 100,
  refillPerTick: 5,
});

const content = bindContent({
  roomTypes: [roomType('bedroom', ['rest']), roomType('cafe', ['food'])],
  needTypes: [need('rest', true), need('food', false)],
  // G-027a: content declaring a lodging need must say how long a stay lasts, or `bindContent`
  // refuses it. G-027b adds the other way out. No want line is declared: nothing here forms a
  // need vector by living forward — every guest below is written by hand in the v6 shape — so
  // there is no arrival for a line to be the starting point of.
  guestRules: [{ id: 'houseRules', name: 'House Rules', stayDurationTicks: 20, toleranceTicks: 100 }],
});

/** The v6 -> v7 step itself. Index 5, the sixth link. */
const step = MIGRATIONS[5]!;

/**
 * A v6 world with something to migrate: one guest carrying a MET need and a PENDING one,
 * and a tally row that already counted somebody out.
 *
 * Built as loose JSON rather than through a typed constructor, because a v6 world cannot be
 * expressed in this build's types — which is the whole reason a migration exists.
 */
const v6World = (): Record<string, unknown> => {
  // EVERY FIELD LATER THAN v6 COMES OFF THE BASE. `createWorld` builds a world in THIS
  // build's shape, and a v6 world is one that predates each of them — so leaving one on
  // hands its migration a value it correctly refuses to overwrite. `reviewOutcomes` is the
  // first top-level field to be added since this helper was written (G-019), which is why
  // the strip is only needed now; the earlier steps reshape fields the v6 shape already had.
  // AND THE v17 DEPTH COMES OFF (G-034a): a v6 plot had four edges, not six, because the row
  // axis did not exist — and `migrateV16ToV17` refuses a plot that already names one.
  const { reviewOutcomes: _laterThanV6, ...base } = stripDepth(
    createWorld(3, content) as unknown as Record<string, unknown>,
  );
  return {
    ...base,
    guests: {
      nextId: 2,
      list: [
        {
          id: 1,
          arrivedTick: 0,
          roomEntityId: 0,
          engagement: null,
          needs: [
            { needId: 'food', patienceRemaining: 90, progressRemaining: 0 },
            { needId: 'rest', patienceRemaining: 80, progressRemaining: 12 },
          ],
        },
      ],
    },
    guestOutcomes: { arrived: 4, satisfied: 2, unsatisfied: 1, evicted: 0 },
    needOutcomes: [
      { needId: 'food', met: 2, unmet: 1 },
      { needId: 'rest', met: 3, unmet: 0 },
    ],
  };
};

type MigratedWorld = {
  guests: { list: { needs: NeedState[] }[] };
  needOutcomes: { needId: string; met: number; unmet: number; metByItem: number }[];
};

describe('the chain runs THROUGH v7, and the shape of it is checkable (G-013)', () => {
  it('ships one step per version, and the 6 -> 7 step is still the sixth of them', () => {
    // The title said "reaches v7" and "six steps" until G-015, which is what a file owning
    // the CURRENT era says. This file stopped owning it when v8 arrived, and the assertions
    // below already knew: v7 is now a stop on the way rather than the end of the line. The
    // absolute went at G-014b (v9) — an era pin in a file that disclaims the era is a line
    // that has to be edited at every bump and asserts nothing this file is about.
    expect(MIN_SUPPORTED_SCHEMA_VERSION).toBe(1);
    expect(MIGRATIONS).toHaveLength(SAVE_SCHEMA_VERSION - MIN_SUPPORTED_SCHEMA_VERSION);
    expect([step.from, step.to]).toEqual([6, 7]);
  });
});

describe('v6 -> v7 attributes what the era can attribute, and invents nothing (G-013)', () => {
  it("gives a MET need metBy 'room', because in the v6 era nothing else could serve one", () => {
    const migrated = step.migrate(v6World()) as MigratedWorld;
    const needs = migrated.guests.list[0]!.needs;
    expect(needs.find((entry) => entry.needId === 'food')).toEqual({
      needId: 'food',
      patienceRemaining: 90,
      progressRemaining: 0,
      metBy: 'room',
    });
  });

  it('leaves a PENDING need attributed to nothing, because nothing has finished it', () => {
    const migrated = step.migrate(v6World()) as MigratedWorld;
    const needs = migrated.guests.list[0]!.needs;
    expect(needs.find((entry) => entry.needId === 'rest')?.metBy).toBe(null);
  });

  it('gives every tally row metByItem 0 — exactly true, since no item ever delivered one', () => {
    const migrated = step.migrate(v6World()) as MigratedWorld;
    expect(migrated.needOutcomes).toEqual([
      { needId: 'food', met: 2, unmet: 1, metByItem: 0 },
      { needId: 'rest', met: 3, unmet: 0, metByItem: 0 },
    ]);
  });

  it('and the result satisfies the invariants this build enforces at load — AFTER THE WHOLE CHAIN', () => {
    // The point of the two defaults: a migrated world is not merely well-typed, it passes
    // the same checks a world this build produced would. If `metBy` defaulted to `null` for
    // a met need — the lazier choice — this would throw.
    //
    // IT WALKS EVERY REMAINING STEP, AND UNTIL G-014b IT DID NOT. This assertion used to run
    // against the v7 INTERMEDIATE and pass, because v7 was the end of the line when it was
    // written. `assertNeedVector` and `assertNeedOutcomes` describe the CURRENT shape — v9
    // added `abandonCount` and `abandoned` — so a v7 world correctly fails them, and the old
    // form was asserting that an intermediate satisfies invariants nothing ever applies to
    // one. `deserialise` runs the whole chain and then checks; so does this now.
    let migrated: unknown = step.migrate(v6World());
    for (const later of MIGRATIONS.filter((entry) => entry.from >= step.to)) migrated = later.migrate(migrated);
    const walked = migrated as { guests: { list: { needs: NeedState[] }[] }; needOutcomes: readonly NeedOutcome[] };
    expect(() => assertNeedVector(walked.guests.list[0]!.needs, 1)).not.toThrow();
    expect(() => assertNeedOutcomes(walked.needOutcomes, 3)).not.toThrow();
  });

  it('attributes a need THIS CONTENT DOES NOT DEFINE, because it reads the bytes and not the table', () => {
    // ADR-0008, as a case that can fail rather than as a restatement. The first version of
    // this test built a second `BoundContent`, never passed it to anything, and asserted
    // `step.migrate(x) === step.migrate(x)` — f(x) === f(x), which is true of every pure
    // function and says nothing about what this one reads. `ai-critic` caught it.
    //
    // A need id no content defines is the case that discriminates: a step that looked the
    // need up to decide how it was served would have to do SOMETHING about not finding it —
    // throw, skip, or leave `metBy` null and produce a world `assertNeedVector` refuses. A
    // step that reads `progressRemaining` and the era it belongs to does not care.
    const world = v6World() as { guests: { list: { needs: Record<string, unknown>[] }[] } };
    world.guests.list[0]!.needs = [
      { needId: 'aNeedNothingDefines', patienceRemaining: 3, progressRemaining: 0 },
      { needId: 'anotherOne', patienceRemaining: 3, progressRemaining: 7 },
    ];
    const migrated = step.migrate(world) as MigratedWorld;
    expect(migrated.guests.list[0]!.needs.map((entry) => entry.metBy)).toEqual(['room', null]);
    // The vector check runs on the END of the chain, not on the v7 intermediate — see the
    // note on the invariants test above, which had the same correction at G-014b.
    let walked: unknown = migrated;
    for (const later of MIGRATIONS.filter((entry) => entry.from >= step.to)) walked = later.migrate(walked);
    const needs = (walked as { guests: { list: { needs: NeedState[] }[] } }).guests.list[0]!.needs;
    expect(() => assertNeedVector(needs, 1)).not.toThrow();
  });

  it('and the structural guard behind that claim is a SOURCE SCAN, not this file', () => {
    // No assertion here can tell "reads the bytes" apart from "reads the table and happens
    // to agree" — the test above discriminates on one contrived input, and a future edit
    // could pass it while still consulting content for the ordinary case. ADR-0008 (3) says
    // that where values coincide the guard must be structural, and it is:
    //
    //     tools/headless/src/migration-scan.build.grid.provider.outcome.travel.save.test.ts
    //
    // a scan asserting `save.ts` names no content lookup in executable code —
    // `providesOf`, `findItemType`, `needTypesInOrder` and the rest. It lives in
    // `tools/headless` because it reads a file and `packages/sim` may not (I1), and it
    // carries `provider` in its name so this goal's exit filter runs it. This case exists
    // to point at it, which is the `grid.save.test.ts` precedent.
    expect(MIGRATIONS).toHaveLength(SAVE_SCHEMA_VERSION - MIN_SUPPORTED_SCHEMA_VERSION);
  });
});

describe('v6 -> v7 refuses to destroy what it cannot have written (G-013)', () => {
  it('refuses a need that already carries an attribution', () => {
    // The refusal every step in this chain makes, and it is reachable rather than
    // decorative: spreading over real state is the one way a migration destroys data.
    const world = v6World() as { guests: { list: { needs: unknown[] }[] } };
    world.guests.list[0]!.needs[0] = {
      needId: 'food',
      patienceRemaining: 90,
      progressRemaining: 0,
      metBy: 'item',
    };
    expect(() => step.migrate(world)).toThrow(/already has a "metBy" field/);
  });

  it('refuses a tally row that already carries a count', () => {
    const world = v6World() as { needOutcomes: unknown[] };
    world.needOutcomes[0] = { needId: 'food', met: 2, unmet: 1, metByItem: 5 };
    expect(() => step.migrate(world)).toThrow(/already has a "metByItem" field/);
  });

  it('refuses a need with no progress to read, rather than guessing whether it was met', () => {
    const world = v6World() as { guests: { list: { needs: unknown[] }[] } };
    world.guests.list[0]!.needs[0] = { needId: 'food', patienceRemaining: 90 };
    expect(() => step.migrate(world)).toThrow(/progressRemaining is missing/);
  });

  it('refuses a non-object world, a missing guest store and a missing tally', () => {
    expect(() => step.migrate(null)).toThrow(/world is not an object/);
    const { guests: _none, ...guestless } = v6World();
    expect(() => step.migrate(guestless)).toThrow(/world.guests is missing/);
    const { needOutcomes: _gone, ...tallyless } = v6World();
    expect(() => step.migrate(tallyless)).toThrow(/world.needOutcomes is missing/);
  });
});

describe('the metBy invariant is enforced at load, in the direction that survives (G-013)', () => {
  const vector = (deficit: number, metBy: unknown): unknown[] => [
    { needId: 'rest', deficit, metBy, abandonCount: 0, unservedTicks: 0 },
  ];

  it('refuses a FULL need that records nothing that served it', () => {
    // Not reachable through the tick — `advanceNeed` writes the field on every served tick —
    // which is exactly why it is checked on the path that faces bytes this build did not
    // write. Without it, `metByItem` would silently under-count and the report's
    // attribution law would fail on a save rather than on the code that broke it.
    expect(() => assertNeedVector(vector(0, null), 1)).toThrow(/records nothing that served/);
  });

  /*
   * `refuses a PENDING need that claims one` WAS HERE AND WAS DELETED AT G-027b. NAMED, NOT
   * DISCOVERED — and the describe above it is now half a title, deliberately.
   *
   * The iff became an implication. "Attributed implies met" was true of a TASK, which had no
   * history: a need that recorded a provider had been finished by it. A STOCK remembers what
   * last served it and then decays, so a half-empty need naming the café that filled it is a
   * true statement about its past rather than a contradiction. The half that survives — full
   * implies attributed — is the case above, and it survives because a stock can only reach full
   * by being served.
   */

  it('refuses an attribution that is neither a room nor an item, and a missing key', () => {
    expect(() => assertNeedVector(vector(0, 'wizard'), 1)).toThrow(/metBy "wizard"/);
    expect(() =>
      assertNeedVector([{ needId: 'rest', deficit: 0, abandonCount: 0, unservedTicks: 0 }], 1),
    ).toThrow(/has no metBy field/);
  });

  it('accepts the two shapes the simulation actually produces', () => {
    expect(() => assertNeedVector(vector(0, 'room'), 1)).not.toThrow();
    expect(() => assertNeedVector(vector(0, 'item'), 1)).not.toThrow();
    expect(() => assertNeedVector(vector(5, null), 1)).not.toThrow();
  });

  it('and the tally refuses more item deliveries than satisfactions', () => {
    // By-room is DERIVED as `met - metByItem`, so this is the clause that stops the report
    // printing a negative count.
    expect(() => assertNeedOutcomes([{ needId: 'rest', met: 2, unmet: 0, metByItem: 3, abandoned: 0, unservedTicks: 0, instanceTicks: 0 }], 5)).toThrow(
      /but only 2 met/,
    );
    expect(() => assertNeedOutcomes([{ needId: 'rest', met: 2, unmet: 0, metByItem: 2, abandoned: 0, unservedTicks: 0, instanceTicks: 0 }], 5)).not.toThrow();
  });
});

describe('a world carrying attributions round-trips (I6)', () => {
  it('serialise -> deserialise -> re-hash is identical, with attributions carried', () => {
    const world = createWorld(9, content);
    expect(hashState(deserialise(serialise(world)))).toBe(hashState(world));
  });

  it('a v6 blob loads, and what it becomes hashes the same however it is reached', () => {
    const blob = JSON.stringify({ schemaVersion: 6, world: v6World() });
    const loaded = deserialise(blob);
    expect(hashState(deserialise(serialise(loaded)))).toBe(hashState(loaded));
    expect((JSON.parse(serialise(loaded)) as { schemaVersion: number }).schemaVersion).toBe(SAVE_SCHEMA_VERSION);
  });
});
