// I6: serialise -> deserialise -> re-hash must reproduce the original state hash, and
// every save carries a schema version with a migration path forward.
//
// The rule that keeps this honest: when you add a field to World, you add it to
// `assertWorldShape` too. A field that round-trips by accident today will be the
// field that is silently missing from someone's save tomorrow.

import { assertBuildOutcomes } from './build.js';
import type { BuildOutcomes } from './build.js';
import { assertEntityStoreInvariants } from './entities.js';
import type { Entity, EntityStore } from './entities.js';
import { assertGridBounds } from './grid.js';
import type { GridBounds } from './grid.js';
import { assertGuestOutcomes, assertGuestStoreInvariants } from './guests.js';
import type { Guest, GuestOutcomes, GuestStore } from './guests.js';
import type { Transaction } from './ledger.js';
import { WORLD_KEYS } from './world.js';
import type { World } from './world.js';

/** Bump this in the same commit as the migration that reaches it. Never edit in place. */
export const SAVE_SCHEMA_VERSION = 4;

/** Oldest version `deserialise` will accept. Raising it drops old saves — human call. */
export const MIN_SUPPORTED_SCHEMA_VERSION = 1;

export type SaveBlob = {
  readonly schemaVersion: number;
  readonly world: World;
};

export type Migration = {
  readonly from: number;
  readonly to: number;
  readonly migrate: (world: unknown) => unknown;
};

/**
 * v1 -> v2: a world that predates guests (G-004).
 *
 * ADR-0006 predicted this exact step and accepted its cost: `fixtures/save-v1.ts` holds
 * the bytes of a real v1 save, `assertWorldShape` rejects unknown top-level keys, and
 * `World` has just gained two. The correct answer was never to regenerate the fixture —
 * a fixture regenerated by the build that broke it agrees with whatever the writer does
 * today, which is the one question it exists to answer — but to write this.
 *
 * WHY THESE DEFAULTS ARE THE READING OF AN OLD SAVE RATHER THAN A CONVENIENT ONE.
 *
 * A v1 world is not a world whose guests were left out of the file. It is a world in
 * which the concept did not exist, so no guest was ever created and no outcome was ever
 * recorded. The bytes say nothing about guests, and the migration must therefore assert
 * nothing about them:
 *
 *   nextId: 1     no guest id has ever been issued. It cannot be 0 — that is NO_GUEST
 *                 and is never allocated — and it must not be higher, which would claim
 *                 ids were handed out to guests the save does not contain.
 *   list: []      nobody is in the hotel.
 *   all counters  nobody has left it either. `arrived: 1` would invent history.
 *
 * The result is provably a legal v2 world rather than merely a plausible one: the
 * conservation law holds (0 === 0 + 0 + 0 + 0), the guest list is trivially ascending,
 * and no reservation can dangle because there is no reservation. No v1 field is
 * renamed, dropped or reinterpreted — tick, rng, ledger, entities and contentHash mean
 * exactly what they meant, which is why the fixture still ticks after loading.
 */
function migrateV1ToV2(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // A "v1" world that already carries these is not a v1 world, and spreading over it
  // would silently discard whatever it did carry. This is the one way this step could
  // destroy data, so it is the one thing it refuses to do. `Object.keys().includes`
  // rather than `in`, because `JSON.parse` makes `__proto__` an own key (G-003).
  const present = Object.keys(world);
  for (const key of ['guests', 'guestOutcomes'] as const) {
    if (present.includes(key)) {
      throw new Error(
        `world already has a "${key}" field, so it is not a v1 world; migrating it would overwrite real state`,
      );
    }
  }
  return {
    ...world,
    guests: { nextId: 1, list: [] },
    guestOutcomes: { arrived: 0, satisfied: 0, unsatisfied: 0, evicted: 0 },
  };
}

/**
 * THE PLOT A v2 WORLD IS CARRIED ONTO, FROZEN AT THE MOMENT v3 WAS DEFINED.
 *
 * These four integers are a LITERAL and must stay one. `createGridBounds()` in `grid.ts`
 * holds the same values today and the two are allowed to diverge later — that divergence
 * is correct, not a bug to repair.
 *
 * Why the duplication is deliberate: a migration's output must be a pure function of its
 * input bytes and of its own era. A migration that read today's constants would turn the
 * same v2 bytes into a DIFFERENT v3 world the moment anyone edits the default plot, so
 * history would drift with the build and the pinned hash of the migrated fixture would
 * become a tripwire on an unrelated change rather than on this migration. Freezing them
 * here costs one copied literal and buys a migration that means the same thing forever.
 */
const V3_MIGRATION_BOUNDS: GridBounds = Object.freeze({
  minFloor: -2,
  maxFloor: 20,
  minColumn: 0,
  maxColumn: 79,
});

/**
 * v2 -> v3: a world that predates the building grid (G-007).
 *
 * ADR-0006 fired for the second time, and this is the first chain to have TWO steps: the
 * permanent v1 fixture now walks 1 -> 2 -> 3. The fixture is not regenerated; this is
 * what carries it.
 *
 * WHY THE PLOT MAY BE DEFAULTED AND A POSITION MAY NOT. The distinction is the whole
 * argument, and it is not the same call G-004 made:
 *
 *   The BOUNDS are a property of the SPACE. No v2 entity has a position, so no v2 fact
 *   can contradict a plot. Giving this world the standard plot says "nothing that
 *   happened in this hotel depended on where its walls were", which is true of a world
 *   in which nothing had a position at all.
 *
 *   A POSITION IS HISTORY. Writing `at: {floor: 0, column: 3}` on a migrated room claims
 *   that room stands there — a claim about the world's contents that these bytes do not
 *   support. And it would not be inert. G-008 refuses a build on an occupied cell, so an
 *   invented position silently blocks a cell the player never touched; G-009 computes
 *   enclosure from placements, so invented neighbours can make an invented room valid.
 *   That is INVENTING HISTORY THAT THE SIMULATION THEN ACTS ON, which is worse than
 *   inventing a counter, and it is why every migrated entity arrives unplaced.
 *
 * So: `at: null` for every entity, and nothing else about them touched. An unplaced room
 * is still a live room — still found, still serving guests, still paying nightly upkeep
 * — so this step changes no economics. What "unplaced" then MEANS to validity is
 * G-009's, which inherits the concept rather than inventing one.
 */
function migrateV2ToV3(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // The one way this step could destroy data — spreading over real state — is the one
  // thing it refuses to do, exactly as the v1 -> v2 step refuses a world with guests.
  // `Object.keys().includes` rather than `in`, because `JSON.parse` makes `__proto__` an
  // own key (G-003).
  if (Object.keys(world).includes('grid')) {
    throw new Error(
      'world already has a "grid" field, so it is not a v2 world; migrating it would overwrite a real plot',
    );
  }

  const entities = world['entities'];
  if (!isRecord(entities)) {
    throw new Error('Save is corrupt: world.entities is missing, so it cannot be carried onto a grid');
  }
  const list = entities['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.entities.list is missing or not an array');
  }
  const placed: unknown[] = list.map((entity, index) => {
    if (!isRecord(entity)) {
      throw new Error(`Save is corrupt: world.entities.list[${index}] is not an object`);
    }
    // Same refusal, one level down: an entity that already stands somewhere did not come
    // from a world that predates positions.
    if (Object.keys(entity).includes('at')) {
      throw new Error(
        `world.entities.list[${index}] already has an "at" field, so it is not a v2 entity; migrating it would overwrite a real position`,
      );
    }
    return { ...entity, at: null };
  });

  return {
    ...world,
    entities: { ...entities, list: placed },
    grid: { ...V3_MIGRATION_BOUNDS },
  };
}

/**
 * THE BUILD COUNTERS A v3 WORLD IS CARRIED ONTO, FROZEN AT THE MOMENT v4 WAS DEFINED.
 *
 * A LITERAL, and it must stay one. `createBuildOutcomes()` in `build.ts` returns the same
 * shape today and the two are allowed to diverge later — that divergence is correct, not
 * a bug to repair (ADR-0008).
 *
 * This is not pedantry about a bag of zeros. `BuildRefusalReason` is a union that WILL
 * grow — G-009's validity rules are the obvious next member. If this step called
 * `createBuildOutcomes()`, the day that member lands the same v3 bytes would start
 * producing a v4 world carrying a counter for a refusal reason that did not exist when
 * those bytes were written, and the pinned hash of the migrated fixture would move on a
 * change that says nothing about it. History would drift with the build.
 *
 * The guard is structural rather than a value assertion, because the two agree today and
 * no assertion can tell the implementations apart: a source scan in
 * `tools/headless/src/migration-scan.build.grid.save.test.ts` forbids this file from naming
 * `createBuildOutcomes` or `BUILD_REFUSAL_REASONS` in executable code.
 */
const V4_MIGRATION_BUILD_OUTCOMES: BuildOutcomes = Object.freeze({
  built: 0,
  demolished: 0,
  refused: Object.freeze({ insufficientFunds: 0, noSuchRoom: 0, occupied: 0, outOfBounds: 0 }),
});

/**
 * v3 -> v4: a world that predates the build loop (G-008).
 *
 * ADR-0006 fires for the third time, and the permanent v1 fixture now walks a THREE-step
 * chain, 1 -> 2 -> 3 -> 4. It is not regenerated; this is what carries it.
 *
 * WHY ZEROS ARE THE READING OF AN OLD SAVE RATHER THAN A CONVENIENT DEFAULT. A v3 world
 * is not a world whose build counters were left out of the file. It is a world in which
 * no player could build at all: the commands did not exist, so no build was made, none
 * was refused, and nothing was demolished by a player. Zero is not a placeholder here, it
 * is the true count. That is a stronger position than the v2 -> v3 step had — there the
 * question was what to do with entities whose positions were genuinely unknown, and the
 * answer was to invent nothing. Here nothing is unknown.
 *
 * The rooms such a world contains were placed by `spawnEntity` or arrived unplaced from
 * the v2 -> v3 step, and `built` deliberately does NOT count them: `built` is "rooms the
 * player built", not "rooms that exist". Claiming otherwise would invent a history of
 * player decisions in a world that had no player, and would break the one cross-subsystem
 * law this goal has — `countConstructionTransactions === built` — for every migrated
 * save, since those rooms were never charged for.
 *
 * No other field is renamed, dropped or reinterpreted, so the fixture still ticks.
 */
function migrateV3ToV4(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // The one way this step could destroy data — spreading over real state — is the one
  // thing it refuses to do, exactly as both earlier steps refuse. `Object.keys().includes`
  // rather than `in`, because `JSON.parse` makes `__proto__` an own key (G-003).
  if (Object.keys(world).includes('buildOutcomes')) {
    throw new Error(
      'world already has a "buildOutcomes" field, so it is not a v3 world; migrating it would overwrite real counters',
    );
  }
  return {
    ...world,
    buildOutcomes: {
      ...V4_MIGRATION_BUILD_OUTCOMES,
      refused: { ...V4_MIGRATION_BUILD_OUTCOMES.refused },
    },
  };
}

/**
 * Ordered, gapless chain from MIN_SUPPORTED_SCHEMA_VERSION to SAVE_SCHEMA_VERSION.
 * `test:save` asserts the chain is complete, so this cannot silently rot.
 *
 * DO NOT invent a version bump to give this array something in it. An unnecessary
 * migration is worse than an untested runner: the runner is exercised against
 * synthetic chains in `save.migrations.test.ts`, which needs no production history.
 */
export const MIGRATIONS: readonly Migration[] = Object.freeze([
  Object.freeze({ from: 1, to: 2, migrate: migrateV1ToV2 }),
  Object.freeze({ from: 2, to: 3, migrate: migrateV2ToV3 }),
  Object.freeze({ from: 3, to: 4, migrate: migrateV3ToV4 }),
]);

/**
 * A version span and the chain that spans it.
 *
 * The production value is `SAVE_SCHEMA`. It is a parameter rather than a global so the
 * runner can be driven against real multi-step chains in tests — a migration runner
 * that has never migrated anything is not a migration path, it is a function that
 * returns. Making the chain injectable is what lets the tests prove the machinery
 * without fabricating a schema change nobody needs.
 */
export type SaveSchema = {
  readonly migrations: readonly Migration[];
  readonly minVersion: number;
  readonly currentVersion: number;
};

/** The chain this build actually ships. */
export const SAVE_SCHEMA: SaveSchema = Object.freeze({
  migrations: MIGRATIONS,
  minVersion: MIN_SUPPORTED_SCHEMA_VERSION,
  currentVersion: SAVE_SCHEMA_VERSION,
});

/**
 * Throws if `schema.migrations` cannot carry the oldest supported save to the current
 * version.
 *
 * The step-count check exists because of how this function used to pass. With an empty
 * `MIGRATIONS` the loop below never ran and the terminal comparison was `1 !== 1`, so
 * "the migration path is complete" was asserted by a function that inspected nothing —
 * the same defect as `check:content` reporting `ok` over zero ids, and as `TICK_PHASES`
 * documenting an order nothing enforced. Requiring EXACTLY `currentVersion - minVersion`
 * steps turns the v1 case from an unvisited loop into a checked fact: zero steps are
 * required and zero are present. A bump to v2 without a migration now fails here.
 */
export function assertMigrationPathComplete(schema: SaveSchema = SAVE_SCHEMA): void {
  const { migrations, minVersion, currentVersion } = schema;
  if (!Number.isInteger(minVersion) || !Number.isInteger(currentVersion)) {
    throw new Error(
      `Migration chain is invalid: version bounds must be integers, got v${String(minVersion)} and v${String(currentVersion)}`,
    );
  }
  if (currentVersion < minVersion) {
    throw new Error(
      `Migration chain is invalid: currentVersion v${currentVersion} is older than minVersion v${minVersion}`,
    );
  }

  const required = currentVersion - minVersion;
  if (migrations.length !== required) {
    throw new Error(
      `Migration chain has ${migrations.length} step(s) but v${minVersion} -> v${currentVersion} requires exactly ${required}. ` +
        'Every version bump needs the migration that reaches it, in the same commit.',
    );
  }

  let version = minVersion;
  for (let i = 0; i < migrations.length; i += 1) {
    const migration = migrations[i];
    if (migration === undefined) {
      throw new Error(`Migration chain is invalid: hole in the chain at index ${i}`);
    }
    // Catches a gap, a duplicate `from` and an out-of-order entry with one comparison:
    // all three are "the step at this position does not start where the last one ended".
    if (migration.from !== version) {
      throw new Error(
        `Migration chain broken: expected a migration from v${version}, found v${migration.from}`,
      );
    }
    if (migration.to !== migration.from + 1) {
      throw new Error(
        `Migration v${migration.from} -> v${migration.to} skips a version; migrate one step at a time`,
      );
    }
    version = migration.to;
  }

  // Unreachable given the three checks above — they force `version` to land exactly on
  // `currentVersion`. Kept because it is the postcondition this function actually
  // promises: if any check above is ever weakened, this fails rather than going quiet.
  if (version !== currentVersion) {
    throw new Error(`Migration chain stops at v${version} but the current version is v${currentVersion}`);
  }
}

/**
 * Carry a parsed save world from `fromVersion` up to `schema.currentVersion`.
 *
 * The step predicate is `migration.from === current`, and the history of that line is
 * worth keeping. It used to be `migration.from >= current`, which silently defeated the
 * only check that could catch a broken chain: given `[1 -> 2, 3 -> 4]` and a v1 save,
 * `>=` ran the v3 -> v4 migration against v2 data, `current` reached 4, the terminal
 * comparison passed, and `deserialise` returned a corrupt world as valid. The gap
 * detector — `assertMigrationPathComplete` — existed the whole time and was never
 * called by `deserialise`: THE GATE FOR THE FAILURE AND THE CODE THAT WOULD FAIL WERE
 * WIRED TO DIFFERENT CIRCUITS. Both halves are fixed here and in `deserialise`.
 *
 * Nothing is mutated: the input is a throwaway `JSON.parse` result and every step
 * returns a new value, so a migration that throws halfway leaves the caller holding
 * exactly what it had before.
 */
export function migrateSaveWorld(
  world: unknown,
  fromVersion: number,
  schema: SaveSchema = SAVE_SCHEMA,
): unknown {
  let migrated: unknown = world;
  let current = fromVersion;

  for (let i = 0; i < schema.migrations.length; i += 1) {
    const migration = schema.migrations[i];
    if (migration === undefined) {
      throw new Error(`Migration chain is invalid: hole in the chain at index ${i}`);
    }
    // Older than this save: it ran before this file was written. Skip it.
    if (migration.from < current) continue;
    // Not older, and not the step we need — the chain has a gap or is out of order.
    // Stop rather than applying a migration to data it was not written for; the
    // terminal check below reports it. This is the case `>=` used to sail through.
    if (migration.from !== current) break;

    let next: unknown;
    try {
      next = migration.migrate(migrated);
    } catch (error) {
      throw new Error(
        `Migration v${migration.from} -> v${migration.to} failed; the save was not loaded`,
        { cause: error },
      );
    }
    if (!isRecord(next)) {
      throw new Error(
        `Migration v${migration.from} -> v${migration.to} returned ${next === undefined ? 'undefined' : typeof next}, not a world object. ` +
          'Every step must return the migrated world; returning nothing would feed the next step garbage.',
      );
    }
    migrated = next;
    current = migration.to;
  }

  if (current !== schema.currentVersion) {
    throw new Error(
      `No migration path from v${fromVersion} to v${schema.currentVersion}: the chain stops at v${current}`,
    );
  }
  return migrated;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Mirrors `describe` in packages/content's registry: a message, never a thrown non-Error. */
const describeError = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

function assertTransaction(value: unknown, index: number): asserts value is Transaction {
  if (!isRecord(value)) {
    throw new Error(`Save is corrupt: ledger[${index}] is not an object`);
  }
  for (const key of ['tick', 'amount'] as const) {
    if (typeof value[key] !== 'number') {
      throw new Error(`Save is corrupt: ledger[${index}].${key} is not a number`);
    }
  }
  // Integer, not merely number (G-005). A float amount loaded from a hand-edited save
  // would flow straight into `balanceOf` and accumulate — the exact platform-dependent
  // drift ADR-0002 forbids, arriving through the one door `appendTransaction` does not
  // guard.
  if (!Number.isInteger(value['amount'])) {
    throw new Error(`Save is corrupt: ledger[${index}].amount is not an integer (money is integer pence, ADR-0002)`);
  }
  // NON-EMPTY, not a member of `TransactionReason` (G-005). The union governs what the
  // sim WRITES; the permanent v1 fixture carries free-text reasons from before it
  // existed, and those bytes are immutable (ADR-0006). What no transaction may ever be
  // is unexplained.
  if (typeof value['reason'] !== 'string' || value['reason'].length === 0) {
    throw new Error(`Save is corrupt: ledger[${index}].reason is not a non-empty string`);
  }
}

function assertEntity(value: unknown, index: number): asserts value is Entity {
  if (!isRecord(value)) {
    throw new Error(`Save is corrupt: world.entities.list[${index}] is not an object`);
  }
  if (typeof value['id'] !== 'number') {
    throw new Error(`Save is corrupt: world.entities.list[${index}].id is not a number`);
  }
  if (typeof value['kind'] !== 'string') {
    throw new Error(`Save is corrupt: world.entities.list[${index}].kind is not a string`);
  }
  // PRESENT, and either null or a cell (G-007). A missing `at` is rejected rather than
  // read as unplaced: `null` is a statement the writer made, an absent key is a save
  // this build did not write and cannot vouch for, and the difference is exactly what
  // the v2 -> v3 migration exists to settle. `Object.keys().includes` rather than `in`,
  // for the `__proto__` reason above.
  if (!Object.keys(value).includes('at')) {
    throw new Error(`Save is corrupt: world.entities.list[${index}].at is missing`);
  }
  const at = value['at'];
  if (at !== null) {
    if (!isRecord(at)) {
      throw new Error(`Save is corrupt: world.entities.list[${index}].at is neither null nor a cell`);
    }
    for (const key of ['floor', 'column'] as const) {
      if (typeof at[key] !== 'number') {
        throw new Error(`Save is corrupt: world.entities.list[${index}].at.${key} is not a number`);
      }
    }
  }
}

function assertGuest(value: unknown, index: number): asserts value is Guest {
  if (!isRecord(value)) {
    throw new Error(`Save is corrupt: world.guests.list[${index}] is not an object`);
  }
  for (const key of ['id', 'arrivedTick', 'roomEntityId', 'patienceRemaining', 'restRemaining'] as const) {
    if (typeof value[key] !== 'number') {
      throw new Error(`Save is corrupt: world.guests.list[${index}].${key} is not a number`);
    }
  }
  if (typeof value['needId'] !== 'string') {
    throw new Error(`Save is corrupt: world.guests.list[${index}].needId is not a string`);
  }
}

/**
 * Structural check over EVERY field of World. Add new fields here when you add them
 * to the World type — this function is the round-trip contract.
 */
export function assertWorldShape(value: unknown): asserts value is World {
  if (!isRecord(value)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // Unknown keys are rejected, not ignored. `worldToJson` is an identity cast, so
  // EVERY own key of this object lands in the state hash — an extra one loads happily
  // and then makes the restored world hash differently from the world it claims to be,
  // which is an I2 divergence introduced from outside the simulation.
  //
  // It also puts the burden where it belongs during a migration: a step that renames a
  // field and forgets to delete the old one fails at load instead of shipping a world
  // carrying both. `WORLD_KEYS.includes` rather than `key in WORLD_KEY_SET`, because
  // `JSON.parse` can hand us an own `__proto__` key and `in` would wave it through.
  for (const key of Object.keys(value)) {
    if (!WORLD_KEYS.includes(key as keyof World)) {
      throw new Error(
        `Save is corrupt: world has unknown top-level key "${key}". Known keys are ${WORLD_KEYS.join(', ')}.`,
      );
    }
  }
  if (typeof value['tick'] !== 'number') {
    throw new Error('Save is corrupt: world.tick is missing or not a number');
  }
  const rng = value['rng'];
  if (!isRecord(rng)) {
    throw new Error('Save is corrupt: world.rng is missing');
  }
  for (const key of ['a', 'b', 'c', 'd'] as const) {
    if (typeof rng[key] !== 'number') {
      throw new Error(`Save is corrupt: world.rng.${key} is missing or not a number`);
    }
  }
  // Which content this world is of (G-002). A save that lost this would load happily
  // under ANY content and then diverge, which is exactly the class of bug the
  // fingerprint exists to make loud.
  const contentHash = value['contentHash'];
  if (typeof contentHash !== 'string' || contentHash.length === 0) {
    throw new Error('Save is corrupt: world.contentHash is missing or not a non-empty string');
  }
  const ledger = value['ledger'];
  if (!Array.isArray(ledger)) {
    throw new Error('Save is corrupt: world.ledger is missing or not an array');
  }
  ledger.forEach(assertTransaction);

  // The plot this hotel is built on (G-007). Validated BEFORE the entity store, because
  // the store's placements are checked against it — a nonsensical plot would otherwise
  // make every placement fail with a message about the wrong thing.
  const grid = value['grid'];
  if (!isRecord(grid)) {
    throw new Error('Save is corrupt: world.grid is missing');
  }
  for (const key of ['minFloor', 'maxFloor', 'minColumn', 'maxColumn'] as const) {
    if (typeof grid[key] !== 'number') {
      throw new Error(`Save is corrupt: world.grid.${key} is missing or not a number`);
    }
  }
  // Same function `createWorld` and the tick would use, so "a valid plot" has one
  // definition. Note what is NOT checked: that the plot equals this build's default.
  // A save's plot is its own, which is what stops a change to the default constants
  // from silently reinterpreting every existing save.
  assertGridBounds(grid as unknown as GridBounds);

  const entities = value['entities'];
  if (!isRecord(entities)) {
    throw new Error('Save is corrupt: world.entities is missing');
  }
  if (typeof entities['nextId'] !== 'number') {
    throw new Error('Save is corrupt: world.entities.nextId is missing or not a number');
  }
  const list = entities['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.entities.list is missing or not an array');
  }
  list.forEach(assertEntity);
  // Shape alone is not enough. A save whose ids are out of order, or whose nextId
  // would collide with a live entity, loads fine and then diverges silently — exactly
  // the failure I6 exists to catch. The check is the SAME function the tick uses when
  // it commits, so "a valid store" has one definition rather than two that drift.
  // Against the plot THIS SAVE carries, not this build's default (see above).
  assertEntityStoreInvariants(entities as unknown as EntityStore, grid as unknown as GridBounds);

  const guests = value['guests'];
  if (!isRecord(guests)) {
    throw new Error('Save is corrupt: world.guests is missing');
  }
  if (typeof guests['nextId'] !== 'number') {
    throw new Error('Save is corrupt: world.guests.nextId is missing or not a number');
  }
  const guestList = guests['list'];
  if (!Array.isArray(guestList)) {
    throw new Error('Save is corrupt: world.guests.list is missing or not an array');
  }
  guestList.forEach(assertGuest);

  const guestOutcomes = value['guestOutcomes'];
  if (!isRecord(guestOutcomes)) {
    throw new Error('Save is corrupt: world.guestOutcomes is missing');
  }
  for (const key of ['arrived', 'satisfied', 'unsatisfied', 'evicted'] as const) {
    if (typeof guestOutcomes[key] !== 'number') {
      throw new Error(`Save is corrupt: world.guestOutcomes.${key} is missing or not a number`);
    }
  }

  // The cross-field half, and the reason this runs at LOAD time and not only in the
  // tick: a save carrying a reservation on a room that is not in the same save would
  // otherwise load happily, report a healthy zero orphans, and be wrong. §6.1's
  // reservation leak is unreachable through the tick, so the only way one can enter the
  // world is from outside it — through here. Same functions the tick uses, so "a valid
  // guest store" has one definition.
  assertGuestStoreInvariants(guests as unknown as GuestStore, entities as unknown as EntityStore);
  assertGuestOutcomes(guestOutcomes as unknown as GuestOutcomes, guests as unknown as GuestStore);

  // The build counters (G-008). Same function the tick calls at its own boundary, so
  // "valid build outcomes" has one definition rather than two that drift. It checks every
  // known refusal reason is present AND that no unknown one is — an extra key would land
  // in the state hash (`worldToJson` is an identity cast) and make the restored world
  // hash differently from the world it claims to be.
  const buildOutcomes = value['buildOutcomes'];
  if (!isRecord(buildOutcomes)) {
    throw new Error('Save is corrupt: world.buildOutcomes is missing');
  }
  for (const key of ['built', 'demolished'] as const) {
    if (typeof buildOutcomes[key] !== 'number') {
      throw new Error(`Save is corrupt: world.buildOutcomes.${key} is missing or not a number`);
    }
  }
  if (!isRecord(buildOutcomes['refused'])) {
    throw new Error('Save is corrupt: world.buildOutcomes.refused is missing');
  }
  assertBuildOutcomes(buildOutcomes as unknown as BuildOutcomes);
}

export function serialise(world: World): string {
  const blob: SaveBlob = { schemaVersion: SAVE_SCHEMA_VERSION, world };
  return JSON.stringify(blob);
}

export function deserialise(json: string, schema: SaveSchema = SAVE_SCHEMA): World {
  // The chain is validated BEFORE it is used, on the real load path. It used to be
  // reachable only from a test, which meant the one function that could detect a broken
  // chain never ran in the place where a broken chain does damage. Loads are rare and
  // the chain is a frozen constant — this is a handful of integer comparisons, and it
  // is not in the tick.
  assertMigrationPathComplete(schema);

  // "This is not JSON" and "this is JSON but it is not a save" are different mistakes
  // with different fixes, and neither should surface as a raw parser grammar error —
  // the same reasoning as `parseContentJson` in packages/content, applied to the same
  // problem. A save interrupted mid-write is a likelier real corruption than most of
  // the shapes below, and it used to be the only one that escaped as a bare SyntaxError.
  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch (error) {
    throw new Error(`Save is corrupt: not valid JSON: ${describeError(error)}`);
  }
  if (!isRecord(parsed)) {
    throw new Error('Save is corrupt: top level is not an object');
  }

  const version = parsed['schemaVersion'];
  if (typeof version !== 'number' || !Number.isInteger(version)) {
    throw new Error('Save is corrupt: schemaVersion is missing or not an integer');
  }
  if (version < schema.minVersion) {
    throw new Error(`Save is v${version}; the oldest supported version is v${schema.minVersion}`);
  }
  if (version > schema.currentVersion) {
    throw new Error(
      `Save is v${version}, which is newer than this build (v${schema.currentVersion})`,
    );
  }

  const world = migrateSaveWorld(parsed['world'], version, schema);
  assertWorldShape(world);
  return world;
}
