// I6: serialise -> deserialise -> re-hash must reproduce the original state hash, and
// every save carries a schema version with a migration path forward.
//
// The rule that keeps this honest: when you add a field to World, you add it to
// `assertWorldShape` too. A field that round-trips by accident today will be the
// field that is silently missing from someone's save tomorrow.

import { assertBuildOutcomes } from './build.js';
import type { BuildOutcomes } from './build.js';
import { assertEntityStoreInvariants } from './entities.js';
import type { Entity, EntityStore } from './entities.js';
import { assertGridBounds } from './grid.js';
import type { GridBounds } from './grid.js';
import { assertGuestOutcomes, assertGuestStoreInvariants, departedGuests } from './guests.js';
import type { Guest, GuestOutcomes, GuestStore } from './guests.js';
import type { Transaction } from './ledger.js';
import { assertLoanOutcomes } from './loan.js';
import type { LoanOutcomes } from './loan.js';
import { assertNeedOutcomes } from './needs.js';
import type { NeedOutcome } from './needs.js';
import { assertReviewOutcomes } from './reviews.js';
import type { ReviewOutcomeRow } from './reviews.js';
import { WORLD_KEYS } from './world.js';
import type { World } from './world.js';

/** Bump this in the same commit as the migration that reaches it. Never edit in place. */
export const SAVE_SCHEMA_VERSION = 12;

/** Oldest version `deserialise` will accept. Raising it drops old saves — human call. */
export const MIN_SUPPORTED_SCHEMA_VERSION = 1;

export type SaveBlob = {
  readonly schemaVersion: number;
  readonly world: World;
};

export type Migration = {
  readonly from: number;
  readonly to: number;
  readonly migrate: (world: unknown) => unknown;
};

/**
 * v1 -> v2: a world that predates guests (G-004).
 *
 * ADR-0006 predicted this exact step and accepted its cost: `fixtures/save-v1.ts` holds
 * the bytes of a real v1 save, `assertWorldShape` rejects unknown top-level keys, and
 * `World` has just gained two. The correct answer was never to regenerate the fixture —
 * a fixture regenerated by the build that broke it agrees with whatever the writer does
 * today, which is the one question it exists to answer — but to write this.
 *
 * WHY THESE DEFAULTS ARE THE READING OF AN OLD SAVE RATHER THAN A CONVENIENT ONE.
 *
 * A v1 world is not a world whose guests were left out of the file. It is a world in
 * which the concept did not exist, so no guest was ever created and no outcome was ever
 * recorded. The bytes say nothing about guests, and the migration must therefore assert
 * nothing about them:
 *
 *   nextId: 1     no guest id has ever been issued. It cannot be 0 — that is NO_GUEST
 *                 and is never allocated — and it must not be higher, which would claim
 *                 ids were handed out to guests the save does not contain.
 *   list: []      nobody is in the hotel.
 *   all counters  nobody has left it either. `arrived: 1` would invent history.
 *
 * The result is provably a legal v2 world rather than merely a plausible one: the
 * conservation law holds (0 === 0 + 0 + 0 + 0), the guest list is trivially ascending,
 * and no reservation can dangle because there is no reservation. No v1 field is
 * renamed, dropped or reinterpreted — tick, rng, ledger, entities and contentHash mean
 * exactly what they meant, which is why the fixture still ticks after loading.
 */
function migrateV1ToV2(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // A "v1" world that already carries these is not a v1 world, and spreading over it
  // would silently discard whatever it did carry. This is the one way this step could
  // destroy data, so it is the one thing it refuses to do. `Object.keys().includes`
  // rather than `in`, because `JSON.parse` makes `__proto__` an own key (G-003).
  const present = Object.keys(world);
  for (const key of ['guests', 'guestOutcomes'] as const) {
    if (present.includes(key)) {
      throw new Error(
        `world already has a "${key}" field, so it is not a v1 world; migrating it would overwrite real state`,
      );
    }
  }
  return {
    ...world,
    guests: { nextId: 1, list: [] },
    guestOutcomes: { arrived: 0, satisfied: 0, unsatisfied: 0, evicted: 0 },
  };
}

/**
 * THE PLOT A v2 WORLD IS CARRIED ONTO, FROZEN AT THE MOMENT v3 WAS DEFINED.
 *
 * These four integers are a LITERAL and must stay one. `createGridBounds()` in `grid.ts`
 * holds the same values today and the two are allowed to diverge later — that divergence
 * is correct, not a bug to repair.
 *
 * Why the duplication is deliberate: a migration's output must be a pure function of its
 * input bytes and of its own era. A migration that read today's constants would turn the
 * same v2 bytes into a DIFFERENT v3 world the moment anyone edits the default plot, so
 * history would drift with the build and the pinned hash of the migrated fixture would
 * become a tripwire on an unrelated change rather than on this migration. Freezing them
 * here costs one copied literal and buys a migration that means the same thing forever.
 */
const V3_MIGRATION_BOUNDS: GridBounds = Object.freeze({
  minFloor: -2,
  maxFloor: 20,
  minColumn: 0,
  maxColumn: 79,
});

/**
 * v2 -> v3: a world that predates the building grid (G-007).
 *
 * ADR-0006 fired for the second time, and this is the first chain to have TWO steps: the
 * permanent v1 fixture now walks 1 -> 2 -> 3. The fixture is not regenerated; this is
 * what carries it.
 *
 * WHY THE PLOT MAY BE DEFAULTED AND A POSITION MAY NOT. The distinction is the whole
 * argument, and it is not the same call G-004 made:
 *
 *   The BOUNDS are a property of the SPACE. No v2 entity has a position, so no v2 fact
 *   can contradict a plot. Giving this world the standard plot says "nothing that
 *   happened in this hotel depended on where its walls were", which is true of a world
 *   in which nothing had a position at all.
 *
 *   A POSITION IS HISTORY. Writing `at: {floor: 0, column: 3}` on a migrated room claims
 *   that room stands there — a claim about the world's contents that these bytes do not
 *   support. And it would not be inert. G-008 refuses a build on an occupied cell, so an
 *   invented position silently blocks a cell the player never touched; G-009 computes
 *   enclosure from placements, so invented neighbours can make an invented room valid.
 *   That is INVENTING HISTORY THAT THE SIMULATION THEN ACTS ON, which is worse than
 *   inventing a counter, and it is why every migrated entity arrives unplaced.
 *
 * So: `at: null` for every entity, and nothing else about them touched. An unplaced room
 * is still a live room — still found, still serving guests, still paying nightly upkeep
 * — so this step changes no economics. What "unplaced" then MEANS to validity is
 * G-009's, which inherits the concept rather than inventing one.
 */
function migrateV2ToV3(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // The one way this step could destroy data — spreading over real state — is the one
  // thing it refuses to do, exactly as the v1 -> v2 step refuses a world with guests.
  // `Object.keys().includes` rather than `in`, because `JSON.parse` makes `__proto__` an
  // own key (G-003).
  if (Object.keys(world).includes('grid')) {
    throw new Error(
      'world already has a "grid" field, so it is not a v2 world; migrating it would overwrite a real plot',
    );
  }

  const entities = world['entities'];
  if (!isRecord(entities)) {
    throw new Error('Save is corrupt: world.entities is missing, so it cannot be carried onto a grid');
  }
  const list = entities['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.entities.list is missing or not an array');
  }
  const placed: unknown[] = list.map((entity, index) => {
    if (!isRecord(entity)) {
      throw new Error(`Save is corrupt: world.entities.list[${index}] is not an object`);
    }
    // Same refusal, one level down: an entity that already stands somewhere did not come
    // from a world that predates positions.
    if (Object.keys(entity).includes('at')) {
      throw new Error(
        `world.entities.list[${index}] already has an "at" field, so it is not a v2 entity; migrating it would overwrite a real position`,
      );
    }
    return { ...entity, at: null };
  });

  return {
    ...world,
    entities: { ...entities, list: placed },
    grid: { ...V3_MIGRATION_BOUNDS },
  };
}

/**
 * THE BUILD COUNTERS A v3 WORLD IS CARRIED ONTO, FROZEN AT THE MOMENT v4 WAS DEFINED.
 *
 * A LITERAL, and it must stay one. `createBuildOutcomes()` in `build.ts` returns the same
 * shape today and the two are allowed to diverge later — that divergence is correct, not
 * a bug to repair (ADR-0008).
 *
 * This is not pedantry about a bag of zeros. `BuildRefusalReason` is a union that WILL
 * grow — G-009's validity rules are the obvious next member. If this step called
 * `createBuildOutcomes()`, the day that member lands the same v3 bytes would start
 * producing a v4 world carrying a counter for a refusal reason that did not exist when
 * those bytes were written, and the pinned hash of the migrated fixture would move on a
 * change that says nothing about it. History would drift with the build.
 *
 * The guard is structural rather than a value assertion, because the two agree today and
 * no assertion can tell the implementations apart: a source scan in
 * `tools/headless/src/migration-scan.build.grid.provider.outcome.travel.save.test.ts`
 * forbids this file from naming `createBuildOutcomes` or `BUILD_REFUSAL_REASONS` in
 * executable code.
 */
const V4_MIGRATION_BUILD_OUTCOMES: BuildOutcomes = Object.freeze({
  built: 0,
  demolished: 0,
  refused: Object.freeze({ insufficientFunds: 0, noSuchRoom: 0, occupied: 0, outOfBounds: 0 }),
});

/**
 * v3 -> v4: a world that predates the build loop (G-008).
 *
 * ADR-0006 fires for the third time, and the permanent v1 fixture now walks a THREE-step
 * chain, 1 -> 2 -> 3 -> 4. It is not regenerated; this is what carries it.
 *
 * WHY ZEROS ARE THE READING OF AN OLD SAVE RATHER THAN A CONVENIENT DEFAULT. A v3 world
 * is not a world whose build counters were left out of the file. It is a world in which
 * no player could build at all: the commands did not exist, so no build was made, none
 * was refused, and nothing was demolished by a player. Zero is not a placeholder here, it
 * is the true count. That is a stronger position than the v2 -> v3 step had — there the
 * question was what to do with entities whose positions were genuinely unknown, and the
 * answer was to invent nothing. Here nothing is unknown.
 *
 * The rooms such a world contains were placed by `spawnEntity` or arrived unplaced from
 * the v2 -> v3 step, and `built` deliberately does NOT count them: `built` is "rooms the
 * player built", not "rooms that exist". Claiming otherwise would invent a history of
 * player decisions in a world that had no player, and would break the one cross-subsystem
 * law this goal has — `countConstructionTransactions === built` — for every migrated
 * save, since those rooms were never charged for.
 *
 * No other field is renamed, dropped or reinterpreted, so the fixture still ticks.
 */
function migrateV3ToV4(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // The one way this step could destroy data — spreading over real state — is the one
  // thing it refuses to do, exactly as both earlier steps refuse. `Object.keys().includes`
  // rather than `in`, because `JSON.parse` makes `__proto__` an own key (G-003).
  if (Object.keys(world).includes('buildOutcomes')) {
    throw new Error(
      'world already has a "buildOutcomes" field, so it is not a v3 world; migrating it would overwrite real counters',
    );
  }
  return {
    ...world,
    buildOutcomes: {
      ...V4_MIGRATION_BUILD_OUTCOMES,
      refused: { ...V4_MIGRATION_BUILD_OUTCOMES.refused },
    },
  };
}

/**
 * THE LOAN COUNTERS A v4 WORLD IS CARRIED ONTO, FROZEN AT THE MOMENT v5 WAS DEFINED.
 *
 * A LITERAL, and it must stay one. `createLoanOutcomes()` in `loan.ts` returns the same
 * shape today and the two are allowed to diverge later — that divergence is correct, not
 * a bug to repair (ADR-0008).
 *
 * The risk here is the v4 case's exactly: `LoanRefusalReason` is a union that WILL grow —
 * "the plot is full", "the debt is at its ceiling" and M4's bankruptcy state are all
 * plausible members. If this step called `createLoanOutcomes()`, the day one lands the
 * same v4 bytes would start producing a v5 world carrying a counter for a refusal that did
 * not exist when those bytes were written, and the only symptom would be the pinned hash
 * of the migrated fixture moving on an unrelated change.
 *
 * The guard is structural rather than a value assertion, because the two agree today and
 * no assertion can tell the implementations apart: the source scan in
 * `tools/headless/src/migration-scan.build.grid.provider.outcome.travel.save.test.ts`
 * forbids this file from naming `createLoanOutcomes` or `LOAN_REFUSAL_REASONS` in
 * executable code.
 */
const V5_MIGRATION_LOAN_OUTCOMES: LoanOutcomes = Object.freeze({
  drawn: 0,
  refused: Object.freeze({ noLoanOffered: 0, notEligible: 0 }),
});

/**
 * v4 -> v5: a world that predates the loan (G-011).
 *
 * ADR-0006 fires for the fourth time, and the permanent v1 fixture now walks a FOUR-step
 * chain, 1 -> 2 -> 3 -> 4 -> 5. It is not regenerated; this is what carries it.
 *
 * WHY ZEROS ARE THE TRUE COUNT AND NOT A CONVENIENT DEFAULT — the v3 -> v4 argument
 * exactly, and just as strong. A v4 world is not a world whose loan counters were left out
 * of the file. It is a world in which no loan could be drawn at all: the command did not
 * exist, so none was granted and none was refused. Nothing here is unknown.
 *
 * WHAT THIS STEP DELIBERATELY DOES NOT DO IS TOUCH THE LEDGER, and that is the whole of
 * its restraint. G-011 gives a world three new kinds of money — starting capital, a
 * demolition refund, and a loan — and a migrated world receives NONE of them
 * retrospectively. Its opening capital was zero because it opened before capital existed;
 * its past demolitions refunded nothing because they refunded nothing; it owes nothing
 * because it never borrowed. Booking any of them now would invent money in a world that
 * never had it, and — worse than inventing a counter — the simulation would then ACT on it,
 * which is the line the v2 -> v3 step drew about invented positions. `outstandingDebtOf`
 * folds a v5-migrated ledger to exactly 0, because it contains no `loanDraw`.
 *
 * No other field is renamed, dropped or reinterpreted, so the fixture still ticks.
 */
function migrateV4ToV5(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // The one way this step could destroy data — spreading over real state — is the one
  // thing it refuses to do, exactly as all three earlier steps refuse.
  // `Object.keys().includes` rather than `in`, because `JSON.parse` makes `__proto__` an
  // own key (G-003).
  if (Object.keys(world).includes('loanOutcomes')) {
    throw new Error(
      'world already has a "loanOutcomes" field, so it is not a v4 world; migrating it would overwrite real counters',
    );
  }
  return {
    ...world,
    loanOutcomes: {
      ...V5_MIGRATION_LOAN_OUTCOMES,
      refused: { ...V5_MIGRATION_LOAN_OUTCOMES.refused },
    },
  };
}

/**
 * THE NEED TALLY A v5 WORLD IS CARRIED ONTO, FROZEN AT THE MOMENT v6 WAS DEFINED.
 *
 * A LITERAL, and it must stay one. `createNeedOutcomes()` in `needs.ts` returns the same
 * value today and the two are allowed to diverge later — that divergence is correct, not a
 * bug to repair (ADR-0008). The source scan in
 * `tools/headless/src/migration-scan.build.grid.provider.outcome.travel.save.test.ts`
 * forbids this file from naming it in executable code, because the two values coincide and
 * no assertion could tell the implementations apart.
 *
 * EMPTY IS THE TRUE COUNT AND NOT A PLACEHOLDER, and here the argument is unusually clean.
 * A v5 world is not a world whose need tally was left out of the file: it is a world in
 * which a guest formed ONE need and nothing counted what became of it, so no instance of
 * any need type had ever been resolved and recorded. Zero rows is what that world had.
 *
 * IT IS ALSO THE ONLY VALUE THIS STEP COULD HONESTLY WRITE, which is the deeper point. A
 * tally with one row per need type would require knowing what need types exist, and need
 * types are CONTENT — which a migration may not read, because its output must be a pure
 * function of its input bytes and its own era. That constraint is why `NeedOutcome` rows
 * are created lazily at all: the shape of the state was chosen so this step could be
 * honest.
 */
const V6_MIGRATION_NEED_OUTCOMES: readonly NeedOutcome[] = Object.freeze([]);

/**
 * v5 -> v6: a world whose guests formed ONE need each, with no vector and no engagement
 * (G-012).
 *
 * ADR-0006 fires for the fifth time, and the permanent v1 fixture now walks a FIVE-step
 * chain, 1 -> 2 -> 3 -> 4 -> 5 -> 6. It is not regenerated; this is what carries it.
 *
 * THIS IS THE FIRST STEP THAT RESHAPES A GUEST RATHER THAN ADDING A FIELD, and every value
 * it writes comes out of the bytes it was given:
 *
 *   needId, patienceRemaining, restRemaining   ->  a ONE-ENTRY need vector, with
 *                                                  `progressRemaining` carrying
 *                                                  `restRemaining` verbatim.
 *   engagement: null                           ->  it engaged nothing, because engagement
 *                                                  did not exist.
 *
 * NOTHING IS INVENTED, AND THAT IS WHY URGENCY IS DERIVED RATHER THAN STORED. Had the
 * vector carried an `urgency` field, this step would have had to compute
 * `patienceTicks - patienceRemaining` — and `patienceTicks` is content, which is exactly
 * what a migration may not read (ADR-0008). It would have had to write 0 instead, silently
 * handing every migrated guest a fresh full patience. The state shape avoids the question.
 *
 * A ONE-ENTRY VECTOR IS A TRUE STATEMENT ABOUT SUCH A GUEST, not a gap. It formed one
 * need, under content that defined one; it did not form three others and lose them. The
 * consequence is real and is accounted for rather than hidden: when it departs it resolves
 * one row and not the rest, which is why `assertNeedOutcomes` bounds the tally with `<=`
 * instead of the identity that holds for every world `createWorld` produced.
 *
 * No other field is renamed, dropped or reinterpreted, so the fixture still ticks.
 */
function migrateV5ToV6(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // The one way this step could destroy data — spreading over real state — is the one
  // thing it refuses to do, exactly as all four earlier steps refuse.
  // `Object.keys().includes` rather than `in`, because `JSON.parse` makes `__proto__` an
  // own key (G-003).
  if (Object.keys(world).includes('needOutcomes')) {
    throw new Error(
      'world already has a "needOutcomes" field, so it is not a v5 world; migrating it would overwrite a real tally',
    );
  }

  const guests = world['guests'];
  if (!isRecord(guests)) {
    throw new Error('Save is corrupt: world.guests is missing, so its needs cannot be carried onto a vector');
  }
  const list = guests['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.guests.list is missing or not an array');
  }
  const vectored: unknown[] = list.map((guest, index) => {
    if (!isRecord(guest)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}] is not an object`);
    }
    // Same refusal, one level down: a guest that already carries a vector did not come
    // from a world that predates one.
    if (Object.keys(guest).includes('needs')) {
      throw new Error(
        `world.guests.list[${index}] already has a "needs" field, so it is not a v5 guest; migrating it would overwrite a real need vector`,
      );
    }
    const { needId, patienceRemaining, restRemaining, ...rest } = guest;
    if (typeof needId !== 'string' || needId.length === 0) {
      throw new Error(`Save is corrupt: world.guests.list[${index}].needId is missing or not a need id`);
    }
    if (typeof patienceRemaining !== 'number' || typeof restRemaining !== 'number') {
      throw new Error(
        `Save is corrupt: world.guests.list[${index}] is missing patienceRemaining or restRemaining, so its one need cannot be carried`,
      );
    }
    return {
      ...rest,
      engagement: null,
      needs: [{ needId, patienceRemaining, progressRemaining: restRemaining }],
    };
  });

  return {
    ...world,
    guests: { ...guests, list: vectored },
    needOutcomes: [...V6_MIGRATION_NEED_OUTCOMES],
  };
}

/**
 * v6 -> v7: a world in which only ROOMS could provide anything (G-013).
 *
 * ADR-0006 fires for the sixth time, and the permanent v1 fixture now walks a SIX-step
 * chain: 1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7. It is migrated, never regenerated.
 *
 * WHAT THIS STEP ADDS, AND WHY BOTH DEFAULTS ARE STATEMENTS OF FACT RATHER THAN GUESSES.
 * G-013 makes an item a provider, so a satisfaction now has to say what delivered it —
 * `metBy` on each need, `metByItem` on each tally row. A v6 world predates that entirely,
 * and the honest question (the one G-004 and G-007 both had to answer) is *what was true
 * of the era these bytes come from*:
 *
 *   metBy      = 'room' for a MET need, null otherwise. In the v6 era nothing but a room
 *                could serve a need, so every satisfaction recorded in these bytes WAS a
 *                room's. This is not a default standing in for missing information — it is
 *                the only value the era admits, and it is derived from the bytes
 *                (`progressRemaining === 0`) rather than from content.
 *   metByItem  = 0. For the same reason: no item ever delivered anything in a v6 world.
 *
 * ADR-0008 holds throughout: this reads no content and no live constant, so the same v6
 * bytes produce the same v7 world however the shipped table changes afterwards.
 *
 * IT IS NOT TESTED BY THE FIXTURE ALONE, DELIBERATELY. The permanent v1 fixture carries no
 * guests and no tally rows, so this step would run over two empty arrays and prove nothing
 * — ADR-0007's exact shape, a check succeeding while inspecting nothing. `provider.save.test.ts`
 * drives a synthetic v6 world with a met need, a pending need and a populated tally, and
 * watches the values come out.
 */
function migrateV6ToV7(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  const guests = world['guests'];
  if (!isRecord(guests)) {
    throw new Error('Save is corrupt: world.guests is missing, so its needs cannot be attributed');
  }
  const list = guests['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.guests.list is missing or not an array');
  }
  const attributed: unknown[] = list.map((guest, index) => {
    if (!isRecord(guest)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}] is not an object`);
    }
    const needs = guest['needs'];
    if (!Array.isArray(needs)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}].needs is missing or not an array`);
    }
    return {
      ...guest,
      needs: needs.map((need, at) => {
        if (!isRecord(need)) {
          throw new Error(`Save is corrupt: world.guests.list[${index}].needs[${at}] is not an object`);
        }
        // The one way this step could destroy data — overwriting an attribution somebody
        // already made — is the one thing it refuses to do, exactly as all five earlier
        // steps refuse. `Object.keys().includes` rather than `in`, because `JSON.parse`
        // makes `__proto__` an own key (G-003).
        if (Object.keys(need).includes('metBy')) {
          throw new Error(
            `world.guests.list[${index}].needs[${at}] already has a "metBy" field, so it is not a v6 need; migrating it would overwrite a real attribution`,
          );
        }
        const progressRemaining = need['progressRemaining'];
        if (typeof progressRemaining !== 'number') {
          throw new Error(
            `Save is corrupt: world.guests.list[${index}].needs[${at}].progressRemaining is missing, so it cannot be told whether the need was met`,
          );
        }
        return { ...need, metBy: progressRemaining === 0 ? 'room' : null };
      }),
    };
  });

  const needOutcomes = world['needOutcomes'];
  if (!Array.isArray(needOutcomes)) {
    throw new Error('Save is corrupt: world.needOutcomes is missing or not an array');
  }
  const split: unknown[] = needOutcomes.map((row, index) => {
    if (!isRecord(row)) {
      throw new Error(`Save is corrupt: world.needOutcomes[${index}] is not an object`);
    }
    if (Object.keys(row).includes('metByItem')) {
      throw new Error(
        `world.needOutcomes[${index}] already has a "metByItem" field, so it is not a v6 row; migrating it would overwrite a real count`,
      );
    }
    return { ...row, metByItem: 0 };
  });

  return { ...world, guests: { ...guests, list: attributed }, needOutcomes: split };
}

/**
 * THE OUTCOME TABLE A v7 WORLD IS CARRIED ONTO, FROZEN AT THE MOMENT v8 WAS DEFINED.
 *
 * A LITERAL, and every reason is spelled out with its own `0` — the
 * `V4_MIGRATION_BUILD_OUTCOMES` shape, for the identical reason. `createGuestOutcomes()`
 * in `guests.ts` built the same five rows and the two were ALLOWED to diverge later; that
 * divergence is correct rather than a bug to repair (ADR-0008 (1)).
 *
 * **THEY HAVE NOW DIVERGED, AND THE PREDICTION WAS ONLY HALF RIGHT.** This comment expected
 * the union to GAIN a member ("gave up waiting for a lift"). What actually happened at
 * G-027a was a RENAME: `satisfied -> checkedOut` and `gaveUpWaiting -> gaveUp`. The two
 * names above are v7-era spellings and MUST NOT be updated to match the live list — a v7
 * world's rows are carried onto v8's names, and `migrateV11ToV12` renames them onwards from
 * there. A migration that folded the live list would rename these bytes twice, silently, and
 * the only symptom would be a moved fixture hash on an unrelated change.
 *
 * The counts are filled in from the v7 counters below; the ORDER and the MEMBERSHIP are
 * this literal's, so the row list a v7 save migrates onto is fixed forever.
 *
 * ADR-0008 (3): the values coincide with the live constructor today, so no value assertion
 * can tell the two implementations apart. The structural guard is the source scan in
 * `tools/headless/src/migration-scan.build.grid.provider.outcome.travel.save.test.ts`.
 */
const V8_MIGRATION_GUEST_OUTCOMES = Object.freeze([
  Object.freeze({ reason: 'satisfied', count: 0 }),
  Object.freeze({ reason: 'gaveUpWaiting', count: 0 }),
  Object.freeze({ reason: 'evictedRoomGone', count: 0 }),
  Object.freeze({ reason: 'evictedRoomUnusable', count: 0 }),
  Object.freeze({ reason: 'evictedCauseUnrecorded', count: 0 }),
]);

/**
 * v7 -> v8: a world whose stays ended for reasons nobody wrote down (G-015).
 *
 * ADR-0006 fires for the seventh time. `World.guestOutcomes` changes SHAPE rather than
 * gaining a sibling field, and that owes a migration for the same reason a new field does:
 * without one, the same old bytes quietly mean something new. The permanent v1 fixture now
 * walks 1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 -> 8, migrated and never regenerated.
 *
 * WHAT EACH v7 COUNTER MEANS IN v8, ARGUED FROM THE ERA AND NOT FROM CONVENIENCE:
 *
 *   arrived      unchanged. It was never an outcome; it is the left-hand side of the law.
 *   satisfied -> satisfied. The same event under the same name.
 *   unsatisfied -> gaveUpWaiting. NOT A RENAME MADE UP HERE: v7's own field documented
 *                itself as "patience for a room ran out before one was free", which is
 *                that reason stated as a reason. Nothing is lost and nothing is invented.
 *   evicted   -> evictedCauseUnrecorded, AND THIS IS THE POINT OF THE WHOLE STEP. v8
 *                distinguishes "the room was demolished" from "the room is still standing
 *                and stopped being a room". A v7 world recorded neither — it counted the
 *                event and threw the cause away — so mapping these to either live reason
 *                would state as fact something these bytes do not say. Both causes really
 *                occurred in the v7 era (`validity.guest.test.ts` drives one of each), so
 *                there is not even a majority to appeal to. The honest v8 value is a row
 *                that means *an eviction from before causes were recorded*, and the tick
 *                can never write it (`TickDepartureReason` excludes it).
 *
 * Reads no content and no live constant, so the same v7 bytes produce the same v8 world
 * however the shipped reason list changes afterwards (ADR-0008).
 *
 * NOT TESTED BY THE FIXTURE ALONE, DELIBERATELY. The permanent v1 fixture reaches this step
 * with three zero counters, over which any mapping whatsoever would look correct — ADR-0007's
 * exact shape. `outcome.save.test.ts` drives a synthetic v7 world with all three counters
 * distinct and non-zero and watches each one land in its own row.
 */
function migrateV7ToV8(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  const outcomes = world['guestOutcomes'];
  if (!isRecord(outcomes)) {
    throw new Error('Save is corrupt: world.guestOutcomes is missing, so its stays cannot be given reasons');
  }
  // The one way this step could destroy data — spreading over a table somebody already
  // has — is the one thing it refuses to do, exactly as all six earlier steps refuse.
  // `Object.keys().includes` rather than `in`, because `JSON.parse` makes `__proto__` an
  // own key (G-003).
  if (Object.keys(outcomes).includes('departures')) {
    throw new Error(
      'world.guestOutcomes already has a "departures" field, so it is not a v7 world; migrating it would overwrite a real table',
    );
  }
  const counters: Record<string, number> = {};
  for (const key of ['arrived', 'satisfied', 'unsatisfied', 'evicted'] as const) {
    const value = outcomes[key];
    if (typeof value !== 'number') {
      throw new Error(
        `Save is corrupt: world.guestOutcomes.${key} is missing or not a number, so this world's stays cannot be counted`,
      );
    }
    counters[key] = value;
  }
  // Mapped by POSITION IN THE FROZEN LITERAL, so the shape of a migrated v7 world is this
  // constant's and the values are the bytes'.
  const carried: Record<string, number> = {
    satisfied: counters['satisfied'] ?? 0,
    gaveUpWaiting: counters['unsatisfied'] ?? 0,
    evictedCauseUnrecorded: counters['evicted'] ?? 0,
  };
  return {
    ...world,
    guestOutcomes: {
      arrived: counters['arrived'] ?? 0,
      departures: V8_MIGRATION_GUEST_OUTCOMES.map((row) => ({
        reason: row.reason,
        count: carried[row.reason] ?? row.count,
      })),
    },
  };
}

/**
 * v8 -> v9: a world whose guests could not change their minds (G-014b).
 *
 * ADR-0006 fires for the eighth time. Two fields arrive in one step and BOTH defaults are
 * argued from the era rather than chosen (ADR-0008) — `ai-critic` named the second one at
 * PLAN, because a migration that only defaults the field you were thinking about is how a
 * save quietly means something new:
 *
 *   guests[].needs[].abandonCount = 0   In the v8 era `reserve` returned early for any
 *                                       engaged guest, so no guest could abandon an
 *                                       engagement at all. Every instance of the count these
 *                                       bytes describe IS zero. Exactly true, not a guess.
 *   needOutcomes[].abandoned      = 0   The same fact one fold downstream: a tally row in a
 *                                       v8 world was accumulated from need vectors that had
 *                                       no abandonment to contribute.
 *
 * Reads no content and no live constant, so the same v8 bytes produce the same v9 world
 * however the shipped margin changes afterwards (ADR-0008). In particular it does NOT
 * consult `abandonMarginOf`: the margin is a fact about the content a world is run under and
 * not about the bytes, and a migration that read it would make an old save's meaning depend
 * on today's `guest-rules.json`.
 *
 * NOT TESTED BY THE FIXTURE ALONE, DELIBERATELY. The permanent v1 fixture carries no guests
 * and no tally rows, so this step would run over two empty arrays and prove nothing —
 * ADR-0007's exact shape, and the reason `migrateV6ToV7` and `migrateV7ToV8` both carry this
 * paragraph. `needs.hysteresis.save.test.ts` drives a synthetic v8 world with a met need, a
 * pending need and a populated tally and watches both zeroes land.
 */
function migrateV8ToV9(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  const guests = world['guests'];
  if (!isRecord(guests)) {
    throw new Error('Save is corrupt: world.guests is missing, so its needs cannot carry an abandonment count');
  }
  const list = guests['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.guests.list is missing or not an array');
  }
  const counted: unknown[] = list.map((guest, index) => {
    if (!isRecord(guest)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}] is not an object`);
    }
    const needs = guest['needs'];
    if (!Array.isArray(needs)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}].needs is missing or not an array`);
    }
    return {
      ...guest,
      needs: needs.map((need, at) => {
        if (!isRecord(need)) {
          throw new Error(`Save is corrupt: world.guests.list[${index}].needs[${at}] is not an object`);
        }
        // The one way this step could destroy data — overwriting a count somebody already
        // made — is the one thing it refuses to do, exactly as all seven earlier steps
        // refuse. `Object.keys().includes` rather than `in`, because `JSON.parse` makes
        // `__proto__` an own key (G-003).
        if (Object.keys(need).includes('abandonCount')) {
          throw new Error(
            `world.guests.list[${index}].needs[${at}] already has an "abandonCount" field, so it is not a v8 need; migrating it would overwrite a real count`,
          );
        }
        return { ...need, abandonCount: 0 };
      }),
    };
  });

  const needOutcomes = world['needOutcomes'];
  if (!Array.isArray(needOutcomes)) {
    throw new Error('Save is corrupt: world.needOutcomes is missing or not an array');
  }
  const tallied: unknown[] = needOutcomes.map((row, index) => {
    if (!isRecord(row)) {
      throw new Error(`Save is corrupt: world.needOutcomes[${index}] is not an object`);
    }
    if (Object.keys(row).includes('abandoned')) {
      throw new Error(
        `world.needOutcomes[${index}] already has an "abandoned" field, so it is not a v8 row; migrating it would overwrite a real count`,
      );
    }
    return { ...row, abandoned: 0 };
  });

  return { ...world, guests: { ...guests, list: counted }, needOutcomes: tallied };
}

/**
 * v9 -> v10: the world gains a REVIEW DISTRIBUTION (G-019).
 *
 * THE DEFAULT IS ARGUED FROM THE ERA AND IS EXACTLY TRUE, NOT A PLACEHOLDER (ADR-0008):
 *
 *   reviewOutcomes = []   In the v9 era a departing guest left no review, because reviews
 *                         did not exist. Every guest these bytes describe has already
 *                         departed or has not; either way NONE of them reviewed anything,
 *                         so an empty distribution is what happened rather than what is
 *                         unknown. Contrast a per-need `waitedTicks`, which G-019 refused
 *                         to add for precisely the opposite reason: a v9 guest DID wait,
 *                         and nothing wrote it down, so any default would be an invention.
 *
 * THE CONSEQUENCE IS STATED HERE RATHER THAN DISCOVERED IN THE REPORT. A migrated v9 world
 * carries departures with no reviews, so `totalReviews < departedGuests` for it — which is
 * why `assertReviewOutcomes` bounds the table with `<=` and only the report, which never
 * loads a save, asserts the exact identity. The `needOutcomes` precedent, verbatim.
 *
 * Reads no content and no live constant, so the same v9 bytes produce the same v10 world
 * however the shipped review scale changes afterwards. That matters more here than it did
 * for the margin: the scale IS content, and a migration that consulted it would make an old
 * save's meaning depend on today's `guest-rules.json`.
 *
 * TESTED BY THE PERMANENT v1 FIXTURE, AND THIS IS THE FIRST STEP IN THREE THAT CAN SAY SO.
 * `migrateV6ToV7`, `migrateV7ToV8` and `migrateV8ToV9` all reach into a guest list the
 * fixture does not have, so each carries a paragraph explaining that the fixture proves
 * nothing for it. This step adds a TOP-LEVEL field, so the fixture walking 1 -> ... -> 10
 * exercises it for real — and `review.save.test.ts` drives the overwrite guard and a
 * populated world besides.
 */
function migrateV9ToV10(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // The one way this step could destroy data — overwriting a distribution somebody already
  // made — is the one thing it refuses to do, exactly as all eight earlier steps refuse.
  // `Object.keys().includes` rather than `in`, because `JSON.parse` makes `__proto__` an
  // own key (G-003).
  if (Object.keys(world).includes('reviewOutcomes')) {
    throw new Error(
      'world already has a "reviewOutcomes" field, so it is not a v9 world; migrating it would overwrite real reviews',
    );
  }
  return { ...world, reviewOutcomes: [] };
}

/**
 * THE STOREY THE DOOR IS ON IN THE v11 ERA, FROZEN AT THE MOMENT v11 WAS DEFINED.
 *
 * A LITERAL, and it must stay one. `GROUND_FLOOR` in `grid.ts` holds the same `0` today and
 * `entranceCell` performs the same clamp; the two are ALLOWED to diverge later and that
 * divergence is correct rather than a bug to repair (ADR-0008 (1)).
 *
 * The risk is not that somebody edits `GROUND_FLOOR` — nothing will. It is that G-023b,
 * G-024 and G-025 change WHERE AN UNPLACED GUEST STANDS: a lobby entity, the foot of the
 * stairs, a reception queue. Every one of those is a live rule about the current build, and
 * a migration that called `entranceCell` would make the same v10 bytes produce a different
 * v11 world on the day one lands — history drifting with the build, with the pinned hash of
 * a migrated fixture as the only symptom.
 *
 * WHAT IS NOT FROZEN, AND MUST NOT BE, IS THE PLOT. The clamp below reads the bounds out of
 * the world being migrated, which is the input bytes and therefore exactly what ADR-0008
 * permits: a v10 save whose plot starts at floor 3 gets its own door, not this build's.
 *
 * The guard is structural, because the values coincide today and no assertion can tell the
 * implementations apart: the source scan in
 * `tools/headless/src/migration-scan.build.grid.provider.outcome.travel.save.test.ts`
 * forbids this file from naming `entranceCell`, `GROUND_FLOOR` or `standingCell` in
 * executable code (ADR-0008 (3)).
 */
const V11_MIGRATION_ENTRANCE_FLOOR = 0;

/**
 * The cell a v10 guest that holds nothing was standing in, from that world's own plot.
 *
 * Not `Math.min`/`Math.max` for its own sake — a clamp written out is a clamp a reader can
 * check against the bounds it names, and this one has to be TOTAL: `assertGridBounds`
 * requires only `minFloor <= maxFloor`, so a legal v10 plot need not contain floor 0, and a
 * migration that assumed it did would emit a world this build then refuses to load.
 */
function v11MigrationEntrance(grid: Record<string, unknown>): { floor: number; column: number } {
  const minFloor = grid['minFloor'];
  const maxFloor = grid['maxFloor'];
  const minColumn = grid['minColumn'];
  if (typeof minFloor !== 'number' || typeof maxFloor !== 'number' || typeof minColumn !== 'number') {
    throw new Error(
      'Save is corrupt: world.grid does not describe a plot, so no entrance can be derived for its guests',
    );
  }
  const floor =
    V11_MIGRATION_ENTRANCE_FLOOR < minFloor
      ? minFloor
      : V11_MIGRATION_ENTRANCE_FLOOR > maxFloor
        ? maxFloor
        : V11_MIGRATION_ENTRANCE_FLOOR;
  return { floor, column: minColumn };
}

/**
 * v10 -> v11: a world whose guests were nowhere (G-023a).
 *
 * ADR-0006 fires for the TENTH time. `Guest` gains `at`, so the permanent v1 fixture
 * describes a world this build cannot load, and the answer is this step. `fixtures/save-v1.ts`
 * HAS A ZERO-LINE DIFF in this change; the walk is 1 -> ... -> 10 -> 11.
 *
 * THE CELL IS DERIVED FROM THE BYTES, AND EVERY BRANCH OF THE DERIVATION IS A FACT THE SAVE
 * ALREADY CONTAINS:
 *
 *   engaged with a placed provider  ->  that provider's cell. A v10 guest using a café was
 *                                       at the café; the save says which café, and the café
 *                                       says which cell.
 *   else lodging in a placed room   ->  that room's cell. Same argument one field over.
 *   else                            ->  the entrance, derived from THIS world's plot. A
 *                                       guest holding nothing was in the doorway waiting,
 *                                       which is the only thing a v10 world can be read as
 *                                       saying about it.
 *
 * AN UNPLACED HOST FALLS THROUGH TO THE NEXT CANDIDATE, and that case is genuinely reachable
 * rather than defensive: every entity carried out of the v2 -> v3 chain has `at: null`,
 * because a world that predated positions could not be given invented ones. Such an entity
 * names no cell, so it cannot answer the question, and the next candidate is asked. If
 * neither can, the entrance can — which is what makes `Guest.at` non-nullable at all.
 *
 * WHY NOT `at: null` AND PLACE THEM LAZILY IN THE TICK. Because the placement rule is going
 * to change: G-024 and G-025 are queues and lifts, and where a guest holding nothing stands
 * is exactly the sort of thing they move. A world loaded from v10 bytes would then be one
 * world under this build and a different one under the next, one tick after loading — the
 * drift ADR-0008 exists to forbid, taking a detour through a tick boundary. Deriving it here
 * pins it to the era that wrote the bytes, which is the same argument `metBy` makes at
 * v6 -> v7.
 *
 * Reads no content and no live constant, so the same v10 bytes produce the same v11 world
 * however the shipped entrance rule changes afterwards (ADR-0008; see
 * `V11_MIGRATION_ENTRANCE_FLOOR` for the freeze and the scan that enforces it).
 *
 * NOT TESTED BY THE FIXTURE, AND SAYING SO IS THE POINT. The permanent v1 fixture's guest
 * list is EMPTY — `migrateV1ToV2` gives it `{nextId: 1, list: []}` and nothing since has put
 * a guest in it — so this step maps over an empty array for the fixture and would report
 * success having inspected nothing (ADR-0007's exact shape, and the paragraph
 * `migrateV6ToV7`, `migrateV7ToV8` and `migrateV8ToV9` all carry). `travel.save.test.ts`
 * drives a hand-written v10 world through every branch above.
 */
function migrateV10ToV11(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  const grid = world['grid'];
  if (!isRecord(grid)) {
    throw new Error('Save is corrupt: world.grid is missing, so its guests cannot be given positions');
  }
  const guests = world['guests'];
  if (!isRecord(guests)) {
    throw new Error('Save is corrupt: world.guests is missing, so its guests cannot be given positions');
  }
  const list = guests['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.guests.list is missing or not an array');
  }
  const entities = world['entities'];
  if (!isRecord(entities)) {
    throw new Error('Save is corrupt: world.entities is missing, so no guest can be placed at what it holds');
  }
  const entityList = entities['list'];
  if (!Array.isArray(entityList)) {
    throw new Error('Save is corrupt: world.entities.list is missing or not an array');
  }
  // The cell of a live entity, or null for one that is unplaced or not there at all. A
  // LINEAR SEARCH, deliberately: this runs once per guest at LOAD, never in a tick, and a
  // migration that assumed the ascending-id ordering of the CURRENT build would be reading a
  // property of this era into bytes from another one.
  const cellOf = (id: unknown): { floor: number; column: number } | null => {
    if (typeof id !== 'number' || id === 0) return null;
    for (const entity of entityList) {
      if (!isRecord(entity) || entity['id'] !== id) continue;
      const at = entity['at'];
      if (!isRecord(at)) return null;
      const floor = at['floor'];
      const column = at['column'];
      return typeof floor === 'number' && typeof column === 'number' ? { floor, column } : null;
    }
    return null;
  };

  const entrance = v11MigrationEntrance(grid);
  const placed: unknown[] = list.map((guest, index) => {
    if (!isRecord(guest)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}] is not an object`);
    }
    // The one way this step could destroy data — overwriting a position somebody already
    // recorded — is the one thing it refuses to do, exactly as all nine earlier steps refuse.
    // `Object.keys().includes` rather than `in`, because `JSON.parse` makes `__proto__` an
    // own key (G-003).
    if (Object.keys(guest).includes('at')) {
      throw new Error(
        `world.guests.list[${index}] already has an "at" field, so it is not a v10 guest; migrating it would overwrite a real position`,
      );
    }
    const engagement = guest['engagement'];
    const at =
      (isRecord(engagement) ? cellOf(engagement['entityId']) : null) ??
      cellOf(guest['roomEntityId']) ??
      entrance;
    // Copied, never shared: two guests standing in the doorway must not hold one object,
    // because `worldToJson` is an identity cast and the shape that reaches the hash should
    // be the shape a `JSON.parse` of it would produce.
    return { ...guest, at: { floor: at.floor, column: at.column } };
  });

  return { ...world, guests: { ...guests, list: placed } };
}

/**
 * THE DEPARTURE ROWS A v11 WORLD CARRIED, FROZEN AT THE MOMENT v12 WAS DEFINED, IN ORDER.
 *
 * A LITERAL, AND THIS IS THE DAY IT DIVERGES FROM `createGuestOutcomes()` — the divergence
 * `V8_MIGRATION_GUEST_OUTCOMES` predicted three goals ago and pre-authorised (ADR-0008 (1)).
 * Those two lists agreed on all five names for four schema versions; they no longer do, and
 * both are correct about the era they describe. A migration that walked the LIVE
 * `GUEST_DEPARTURE_REASONS` would now rename a v7 world's rows too, silently, and the only
 * symptom would be a moved fixture hash on an unrelated change.
 *
 * IT IS A PAIR LIST RATHER THAN TWO PARALLEL ARRAYS, so a row cannot be renamed onto the
 * wrong position by an edit to one of them.
 */
const V12_MIGRATION_DEPARTURE_RENAMES = Object.freeze([
  Object.freeze({ from: 'satisfied', to: 'checkedOut' }),
  Object.freeze({ from: 'gaveUpWaiting', to: 'gaveUp' }),
  Object.freeze({ from: 'evictedRoomGone', to: 'evictedRoomGone' }),
  Object.freeze({ from: 'evictedRoomUnusable', to: 'evictedRoomUnusable' }),
  Object.freeze({ from: 'evictedCauseUnrecorded', to: 'evictedCauseUnrecorded' }),
]);

/**
 * v11 -> v12: a world whose stays ended because a need finished (G-027a, ADR-0017).
 *
 * ADR-0006 fires for the ELEVENTH time. No field arrives and none leaves; two ROW LABELS in
 * `world.guestOutcomes.departures` change, and a label inside hashed state is a schema
 * change exactly as a field is. `fixtures/save-v1.ts` HAS A ZERO-LINE DIFF in this change;
 * the walk is 1 -> ... -> 11 -> 12.
 *
 * ---------------------------------------------------------------------------
 * WHY THE RENAME IS SOUND, AND IT IS NOT "THE SAME POPULATION RENAMED".
 *
 * That defence would be false. A v11 guest counted under `satisfied` departed BECAUSE ITS
 * LODGING NEED COMPLETED — the terminator this goal deletes — and no v12 guest departs for
 * that reason, so the two rows are not filled by the same event at all.
 *
 * What makes the mapping honest is narrower and is checkable: **the two populations coincide
 * under every predicate either era applies to that row.** Everything downstream asks exactly
 * three questions of a departure row, and v11's `satisfied` and v12's `checkedOut` give the
 * same answer to all three:
 *
 *   did this stay pay?        YES, exactly once. `payForStay` was called on the v11
 *                             satisfied path and is called on the v12 checkout path, and on
 *                             no other path in either era — which is why
 *                             `countRoomRevenueTransactions === this row` is a law in both.
 *   was it cut short?         NO. `isCutShort` returned false for `satisfied` and returns
 *                             false for `checkedOut`; the guest left when the stay ended.
 *   may the tick write it?    YES. Both are in `TickDepartureReason`.
 *
 * `gaveUpWaiting -> gaveUp` is the same argument with the answers NO / NO / YES, and the
 * word that leaves is the one that over-narrows: v11's row already covered every way a guest
 * ended its own stay, because waiting for a room was the only one there was.
 *
 * SO THE COUNTS CARRY. What a migrated v12 world says is *this many stays ended without
 * being cut short and having paid*, which is true of those bytes and was true when they were
 * written. What it does NOT claim, and must not be read as claiming, is that those guests
 * stayed 1,440 ticks — they did not, and `stayDurationTicks` is content this migration is
 * forbidden to consult (ADR-0008).
 * ---------------------------------------------------------------------------
 *
 * Reads no content and no live constant, so the same v11 bytes produce the same v12 world
 * however the shipped reason list changes afterwards (ADR-0008; the structural guard is the
 * source scan in `migration-scan.build.grid.provider.outcome.travel.save.test.ts`, which
 * already forbids this file from naming `GUEST_DEPARTURE_REASONS`).
 *
 * THE OVERWRITE GUARD IS A NAME CHECK RATHER THAN A KEY CHECK, because nothing is being
 * ADDED. Every earlier step refuses a document that already carries the field it is about;
 * this one refuses a row that is not spelled the way v11 spelled it — which catches a v12
 * document fed in as v11 (its first row already reads `checkedOut`) and a corrupt table
 * alike. `Object.keys().includes` still guards the one key this step reaches through,
 * because `JSON.parse` makes `__proto__` an own key (G-003).
 *
 * TESTED BY THE PERMANENT v1 FIXTURE, WHICH REACHES THIS STEP WITH FIVE ZERO ROWS — over
 * which any mapping whatsoever would look correct (ADR-0007's exact shape, and the paragraph
 * `migrateV7ToV8` carries). `guest.stay.save.test.ts` drives a synthetic v11 world with all
 * five counters distinct and non-zero and watches each land under its v12 name.
 */
function migrateV11ToV12(world: unknown): unknown {
  if (!isRecord(world)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  const outcomes = world['guestOutcomes'];
  if (!isRecord(outcomes)) {
    throw new Error('Save is corrupt: world.guestOutcomes is missing, so its stays cannot be renamed');
  }
  if (!Object.keys(outcomes).includes('departures')) {
    throw new Error(
      'Save is corrupt: world.guestOutcomes has no "departures" field, so it is not a v11 world',
    );
  }
  const rows = outcomes['departures'];
  if (!Array.isArray(rows)) {
    throw new Error('Save is corrupt: world.guestOutcomes.departures is missing or not an array');
  }
  if (rows.length !== V12_MIGRATION_DEPARTURE_RENAMES.length) {
    throw new Error(
      `Save is corrupt: world.guestOutcomes.departures has ${rows.length} row(s) where a v11 world has ` +
        `${V12_MIGRATION_DEPARTURE_RENAMES.length}; this is not a v11 departure table`,
    );
  }
  // Mapped by POSITION IN THE FROZEN LITERAL, so the shape of a migrated v11 world is this
  // constant's and the counts are the bytes' — `migrateV7ToV8`'s mechanism exactly.
  const renamed = V12_MIGRATION_DEPARTURE_RENAMES.map((rename, index) => {
    const row = rows[index];
    if (!isRecord(row)) {
      throw new Error(`Save is corrupt: world.guestOutcomes.departures[${index}] is not an object`);
    }
    if (row['reason'] !== rename.from) {
      throw new Error(
        `world.guestOutcomes.departures[${index}] is "${String(row['reason'])}" where a v11 world carries ` +
          `"${rename.from}", so it is not a v11 departure table; migrating it would rename a row onto a reason ` +
          'it does not describe',
      );
    }
    const count = row['count'];
    if (typeof count !== 'number') {
      throw new Error(
        `Save is corrupt: world.guestOutcomes.departures[${index}].count is missing or not a number, so this ` +
          "world's stays cannot be counted",
      );
    }
    return { reason: rename.to, count };
  });
  return { ...world, guestOutcomes: { ...outcomes, departures: renamed } };
}

/**
 * Ordered, gapless chain from MIN_SUPPORTED_SCHEMA_VERSION to SAVE_SCHEMA_VERSION.
 * `test:save` asserts the chain is complete, so this cannot silently rot.
 *
 * DO NOT invent a version bump to give this array something in it. An unnecessary
 * migration is worse than an untested runner: the runner is exercised against
 * synthetic chains in `save.migrations.test.ts`, which needs no production history.
 */
export const MIGRATIONS: readonly Migration[] = Object.freeze([
  Object.freeze({ from: 1, to: 2, migrate: migrateV1ToV2 }),
  Object.freeze({ from: 2, to: 3, migrate: migrateV2ToV3 }),
  Object.freeze({ from: 3, to: 4, migrate: migrateV3ToV4 }),
  Object.freeze({ from: 4, to: 5, migrate: migrateV4ToV5 }),
  Object.freeze({ from: 5, to: 6, migrate: migrateV5ToV6 }),
  Object.freeze({ from: 6, to: 7, migrate: migrateV6ToV7 }),
  Object.freeze({ from: 7, to: 8, migrate: migrateV7ToV8 }),
  Object.freeze({ from: 8, to: 9, migrate: migrateV8ToV9 }),
  Object.freeze({ from: 9, to: 10, migrate: migrateV9ToV10 }),
  Object.freeze({ from: 10, to: 11, migrate: migrateV10ToV11 }),
  Object.freeze({ from: 11, to: 12, migrate: migrateV11ToV12 }),
]);

/**
 * A version span and the chain that spans it.
 *
 * The production value is `SAVE_SCHEMA`. It is a parameter rather than a global so the
 * runner can be driven against real multi-step chains in tests — a migration runner
 * that has never migrated anything is not a migration path, it is a function that
 * returns. Making the chain injectable is what lets the tests prove the machinery
 * without fabricating a schema change nobody needs.
 */
export type SaveSchema = {
  readonly migrations: readonly Migration[];
  readonly minVersion: number;
  readonly currentVersion: number;
};

/** The chain this build actually ships. */
export const SAVE_SCHEMA: SaveSchema = Object.freeze({
  migrations: MIGRATIONS,
  minVersion: MIN_SUPPORTED_SCHEMA_VERSION,
  currentVersion: SAVE_SCHEMA_VERSION,
});

/**
 * Throws if `schema.migrations` cannot carry the oldest supported save to the current
 * version.
 *
 * The step-count check exists because of how this function used to pass. With an empty
 * `MIGRATIONS` the loop below never ran and the terminal comparison was `1 !== 1`, so
 * "the migration path is complete" was asserted by a function that inspected nothing —
 * the same defect as `check:content` reporting `ok` over zero ids, and as `TICK_PHASES`
 * documenting an order nothing enforced. Requiring EXACTLY `currentVersion - minVersion`
 * steps turns the v1 case from an unvisited loop into a checked fact: zero steps are
 * required and zero are present. A bump to v2 without a migration now fails here.
 */
export function assertMigrationPathComplete(schema: SaveSchema = SAVE_SCHEMA): void {
  const { migrations, minVersion, currentVersion } = schema;
  if (!Number.isInteger(minVersion) || !Number.isInteger(currentVersion)) {
    throw new Error(
      `Migration chain is invalid: version bounds must be integers, got v${String(minVersion)} and v${String(currentVersion)}`,
    );
  }
  if (currentVersion < minVersion) {
    throw new Error(
      `Migration chain is invalid: currentVersion v${currentVersion} is older than minVersion v${minVersion}`,
    );
  }

  const required = currentVersion - minVersion;
  if (migrations.length !== required) {
    throw new Error(
      `Migration chain has ${migrations.length} step(s) but v${minVersion} -> v${currentVersion} requires exactly ${required}. ` +
        'Every version bump needs the migration that reaches it, in the same commit.',
    );
  }

  let version = minVersion;
  for (let i = 0; i < migrations.length; i += 1) {
    const migration = migrations[i];
    if (migration === undefined) {
      throw new Error(`Migration chain is invalid: hole in the chain at index ${i}`);
    }
    // Catches a gap, a duplicate `from` and an out-of-order entry with one comparison:
    // all three are "the step at this position does not start where the last one ended".
    if (migration.from !== version) {
      throw new Error(
        `Migration chain broken: expected a migration from v${version}, found v${migration.from}`,
      );
    }
    if (migration.to !== migration.from + 1) {
      throw new Error(
        `Migration v${migration.from} -> v${migration.to} skips a version; migrate one step at a time`,
      );
    }
    version = migration.to;
  }

  // Unreachable given the three checks above — they force `version` to land exactly on
  // `currentVersion`. Kept because it is the postcondition this function actually
  // promises: if any check above is ever weakened, this fails rather than going quiet.
  if (version !== currentVersion) {
    throw new Error(`Migration chain stops at v${version} but the current version is v${currentVersion}`);
  }
}

/**
 * Carry a parsed save world from `fromVersion` up to `schema.currentVersion`.
 *
 * The step predicate is `migration.from === current`, and the history of that line is
 * worth keeping. It used to be `migration.from >= current`, which silently defeated the
 * only check that could catch a broken chain: given `[1 -> 2, 3 -> 4]` and a v1 save,
 * `>=` ran the v3 -> v4 migration against v2 data, `current` reached 4, the terminal
 * comparison passed, and `deserialise` returned a corrupt world as valid. The gap
 * detector — `assertMigrationPathComplete` — existed the whole time and was never
 * called by `deserialise`: THE GATE FOR THE FAILURE AND THE CODE THAT WOULD FAIL WERE
 * WIRED TO DIFFERENT CIRCUITS. Both halves are fixed here and in `deserialise`.
 *
 * Nothing is mutated: the input is a throwaway `JSON.parse` result and every step
 * returns a new value, so a migration that throws halfway leaves the caller holding
 * exactly what it had before.
 */
export function migrateSaveWorld(
  world: unknown,
  fromVersion: number,
  schema: SaveSchema = SAVE_SCHEMA,
): unknown {
  let migrated: unknown = world;
  let current = fromVersion;

  for (let i = 0; i < schema.migrations.length; i += 1) {
    const migration = schema.migrations[i];
    if (migration === undefined) {
      throw new Error(`Migration chain is invalid: hole in the chain at index ${i}`);
    }
    // Older than this save: it ran before this file was written. Skip it.
    if (migration.from < current) continue;
    // Not older, and not the step we need — the chain has a gap or is out of order.
    // Stop rather than applying a migration to data it was not written for; the
    // terminal check below reports it. This is the case `>=` used to sail through.
    if (migration.from !== current) break;

    let next: unknown;
    try {
      next = migration.migrate(migrated);
    } catch (error) {
      throw new Error(
        `Migration v${migration.from} -> v${migration.to} failed; the save was not loaded`,
        { cause: error },
      );
    }
    if (!isRecord(next)) {
      throw new Error(
        `Migration v${migration.from} -> v${migration.to} returned ${next === undefined ? 'undefined' : typeof next}, not a world object. ` +
          'Every step must return the migrated world; returning nothing would feed the next step garbage.',
      );
    }
    migrated = next;
    current = migration.to;
  }

  if (current !== schema.currentVersion) {
    throw new Error(
      `No migration path from v${fromVersion} to v${schema.currentVersion}: the chain stops at v${current}`,
    );
  }
  return migrated;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Mirrors `describe` in packages/content's registry: a message, never a thrown non-Error. */
const describeError = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

function assertTransaction(value: unknown, index: number): asserts value is Transaction {
  if (!isRecord(value)) {
    throw new Error(`Save is corrupt: ledger[${index}] is not an object`);
  }
  for (const key of ['tick', 'amount'] as const) {
    if (typeof value[key] !== 'number') {
      throw new Error(`Save is corrupt: ledger[${index}].${key} is not a number`);
    }
  }
  // Integer, not merely number (G-005). A float amount loaded from a hand-edited save
  // would flow straight into `balanceOf` and accumulate — the exact platform-dependent
  // drift ADR-0002 forbids, arriving through the one door `appendTransaction` does not
  // guard.
  if (!Number.isInteger(value['amount'])) {
    throw new Error(`Save is corrupt: ledger[${index}].amount is not an integer (money is integer pence, ADR-0002)`);
  }
  // NON-EMPTY, not a member of `TransactionReason` (G-005). The union governs what the
  // sim WRITES; the permanent v1 fixture carries free-text reasons from before it
  // existed, and those bytes are immutable (ADR-0006). What no transaction may ever be
  // is unexplained.
  if (typeof value['reason'] !== 'string' || value['reason'].length === 0) {
    throw new Error(`Save is corrupt: ledger[${index}].reason is not a non-empty string`);
  }
}

function assertEntity(value: unknown, index: number): asserts value is Entity {
  if (!isRecord(value)) {
    throw new Error(`Save is corrupt: world.entities.list[${index}] is not an object`);
  }
  if (typeof value['id'] !== 'number') {
    throw new Error(`Save is corrupt: world.entities.list[${index}].id is not a number`);
  }
  if (typeof value['kind'] !== 'string') {
    throw new Error(`Save is corrupt: world.entities.list[${index}].kind is not a string`);
  }
  // PRESENT, and either null or a cell (G-007). A missing `at` is rejected rather than
  // read as unplaced: `null` is a statement the writer made, an absent key is a save
  // this build did not write and cannot vouch for, and the difference is exactly what
  // the v2 -> v3 migration exists to settle. `Object.keys().includes` rather than `in`,
  // for the `__proto__` reason above.
  if (!Object.keys(value).includes('at')) {
    throw new Error(`Save is corrupt: world.entities.list[${index}].at is missing`);
  }
  const at = value['at'];
  if (at !== null) {
    if (!isRecord(at)) {
      throw new Error(`Save is corrupt: world.entities.list[${index}].at is neither null nor a cell`);
    }
    for (const key of ['floor', 'column'] as const) {
      if (typeof at[key] !== 'number') {
        throw new Error(`Save is corrupt: world.entities.list[${index}].at.${key} is not a number`);
      }
    }
  }
}

function assertGuest(value: unknown, index: number): asserts value is Guest {
  if (!isRecord(value)) {
    throw new Error(`Save is corrupt: world.guests.list[${index}] is not an object`);
  }
  for (const key of ['id', 'arrivedTick', 'roomEntityId'] as const) {
    if (typeof value[key] !== 'number') {
      throw new Error(`Save is corrupt: world.guests.list[${index}].${key} is not a number`);
    }
  }
  // WHERE IT IS STANDING (G-023a). Shape only here — a record of two numbers — because
  // `assertGuestStoreInvariants` below owns what a valid POSITION is, against the plot this
  // save carries, and that definition is shared with the tick rather than written twice.
  //
  // NOT `null`, WHICH IS THE ONE PLACE THIS DIFFERS FROM `Entity.at`. An entity may honestly
  // be nowhere; a guest may not, because `migrateV10ToV11` can always read a cell out of the
  // bytes. So `at: null` here is a save this build did not write and cannot vouch for, and
  // it is refused rather than quietly re-placed a tick later.
  const at = value['at'];
  if (!isRecord(at)) {
    throw new Error(`Save is corrupt: world.guests.list[${index}].at is missing or not a cell`);
  }
  for (const key of ['floor', 'column'] as const) {
    if (typeof at[key] !== 'number') {
      throw new Error(`Save is corrupt: world.guests.list[${index}].at.${key} is not a number`);
    }
  }
  // The need vector (G-012). Shape only here — that it is an array of records with the
  // right primitive types — because `assertGuestStoreInvariants` below owns what a VALID
  // vector is, and that definition is shared with the tick rather than written twice.
  const needs = value['needs'];
  if (!Array.isArray(needs)) {
    throw new Error(`Save is corrupt: world.guests.list[${index}].needs is missing or not an array`);
  }
  needs.forEach((need: unknown, needIndex: number) => {
    if (!isRecord(need)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}].needs[${needIndex}] is not an object`);
    }
    if (typeof need['needId'] !== 'string') {
      throw new Error(`Save is corrupt: world.guests.list[${index}].needs[${needIndex}].needId is not a string`);
    }
    for (const key of ['patienceRemaining', 'progressRemaining'] as const) {
      if (typeof need[key] !== 'number') {
        throw new Error(`Save is corrupt: world.guests.list[${index}].needs[${needIndex}].${key} is not a number`);
      }
    }
  });
  // PRESENT, and either null or an engagement (G-012) — the `Entity.at` contract exactly.
  // A missing key is rejected rather than read as "engaged with nothing": `null` is a
  // statement the writer made, an absent key is a save this build did not write, and the
  // difference is what the v5 -> v6 migration exists to settle. `Object.keys().includes`
  // rather than `in`, for the `__proto__` reason above.
  if (!Object.keys(value).includes('engagement')) {
    throw new Error(`Save is corrupt: world.guests.list[${index}].engagement is missing`);
  }
  const engagement = value['engagement'];
  if (engagement !== null) {
    if (!isRecord(engagement)) {
      throw new Error(`Save is corrupt: world.guests.list[${index}].engagement is neither null nor an engagement`);
    }
    if (typeof engagement['entityId'] !== 'number') {
      throw new Error(`Save is corrupt: world.guests.list[${index}].engagement.entityId is not a number`);
    }
    if (typeof engagement['needId'] !== 'string') {
      throw new Error(`Save is corrupt: world.guests.list[${index}].engagement.needId is not a string`);
    }
  }
}

/**
 * Structural check over EVERY field of World. Add new fields here when you add them
 * to the World type — this function is the round-trip contract.
 */
export function assertWorldShape(value: unknown): asserts value is World {
  if (!isRecord(value)) {
    throw new Error('Save is corrupt: world is not an object');
  }
  // Unknown keys are rejected, not ignored. `worldToJson` is an identity cast, so
  // EVERY own key of this object lands in the state hash — an extra one loads happily
  // and then makes the restored world hash differently from the world it claims to be,
  // which is an I2 divergence introduced from outside the simulation.
  //
  // It also puts the burden where it belongs during a migration: a step that renames a
  // field and forgets to delete the old one fails at load instead of shipping a world
  // carrying both. `WORLD_KEYS.includes` rather than `key in WORLD_KEY_SET`, because
  // `JSON.parse` can hand us an own `__proto__` key and `in` would wave it through.
  for (const key of Object.keys(value)) {
    if (!WORLD_KEYS.includes(key as keyof World)) {
      throw new Error(
        `Save is corrupt: world has unknown top-level key "${key}". Known keys are ${WORLD_KEYS.join(', ')}.`,
      );
    }
  }
  if (typeof value['tick'] !== 'number') {
    throw new Error('Save is corrupt: world.tick is missing or not a number');
  }
  const rng = value['rng'];
  if (!isRecord(rng)) {
    throw new Error('Save is corrupt: world.rng is missing');
  }
  for (const key of ['a', 'b', 'c', 'd'] as const) {
    if (typeof rng[key] !== 'number') {
      throw new Error(`Save is corrupt: world.rng.${key} is missing or not a number`);
    }
  }
  // Which content this world is of (G-002). A save that lost this would load happily
  // under ANY content and then diverge, which is exactly the class of bug the
  // fingerprint exists to make loud.
  const contentHash = value['contentHash'];
  if (typeof contentHash !== 'string' || contentHash.length === 0) {
    throw new Error('Save is corrupt: world.contentHash is missing or not a non-empty string');
  }
  const ledger = value['ledger'];
  if (!Array.isArray(ledger)) {
    throw new Error('Save is corrupt: world.ledger is missing or not an array');
  }
  ledger.forEach(assertTransaction);

  // The plot this hotel is built on (G-007). Validated BEFORE the entity store, because
  // the store's placements are checked against it — a nonsensical plot would otherwise
  // make every placement fail with a message about the wrong thing.
  const grid = value['grid'];
  if (!isRecord(grid)) {
    throw new Error('Save is corrupt: world.grid is missing');
  }
  for (const key of ['minFloor', 'maxFloor', 'minColumn', 'maxColumn'] as const) {
    if (typeof grid[key] !== 'number') {
      throw new Error(`Save is corrupt: world.grid.${key} is missing or not a number`);
    }
  }
  // Same function `createWorld` and the tick would use, so "a valid plot" has one
  // definition. Note what is NOT checked: that the plot equals this build's default.
  // A save's plot is its own, which is what stops a change to the default constants
  // from silently reinterpreting every existing save.
  assertGridBounds(grid as unknown as GridBounds);

  const entities = value['entities'];
  if (!isRecord(entities)) {
    throw new Error('Save is corrupt: world.entities is missing');
  }
  if (typeof entities['nextId'] !== 'number') {
    throw new Error('Save is corrupt: world.entities.nextId is missing or not a number');
  }
  const list = entities['list'];
  if (!Array.isArray(list)) {
    throw new Error('Save is corrupt: world.entities.list is missing or not an array');
  }
  list.forEach(assertEntity);
  // Shape alone is not enough. A save whose ids are out of order, or whose nextId
  // would collide with a live entity, loads fine and then diverges silently — exactly
  // the failure I6 exists to catch. The check is the SAME function the tick uses when
  // it commits, so "a valid store" has one definition rather than two that drift.
  // Against the plot THIS SAVE carries, not this build's default (see above).
  assertEntityStoreInvariants(entities as unknown as EntityStore, grid as unknown as GridBounds);

  const guests = value['guests'];
  if (!isRecord(guests)) {
    throw new Error('Save is corrupt: world.guests is missing');
  }
  if (typeof guests['nextId'] !== 'number') {
    throw new Error('Save is corrupt: world.guests.nextId is missing or not a number');
  }
  const guestList = guests['list'];
  if (!Array.isArray(guestList)) {
    throw new Error('Save is corrupt: world.guests.list is missing or not an array');
  }
  guestList.forEach(assertGuest);

  const guestOutcomes = value['guestOutcomes'];
  if (!isRecord(guestOutcomes)) {
    throw new Error('Save is corrupt: world.guestOutcomes is missing');
  }
  if (typeof guestOutcomes['arrived'] !== 'number') {
    throw new Error('Save is corrupt: world.guestOutcomes.arrived is missing or not a number');
  }
  // THE TABLE (G-015). Shape first, then `assertGuestOutcomes` below for the reasons, the
  // order and the conservation law — the same function the tick calls at its own boundary,
  // so "a valid outcome table" has one definition rather than two that drift.
  const departures = guestOutcomes['departures'];
  if (!Array.isArray(departures)) {
    throw new Error('Save is corrupt: world.guestOutcomes.departures is missing or not an array');
  }
  departures.forEach((row: unknown, index: number) => {
    if (!isRecord(row)) {
      throw new Error(`Save is corrupt: world.guestOutcomes.departures[${index}] is not an object`);
    }
    if (typeof row['reason'] !== 'string') {
      throw new Error(`Save is corrupt: world.guestOutcomes.departures[${index}].reason is not a string`);
    }
    if (typeof row['count'] !== 'number') {
      throw new Error(`Save is corrupt: world.guestOutcomes.departures[${index}].count is not a number`);
    }
    // An extra key would land in the state hash (`worldToJson` is an identity cast) and
    // make the restored world hash differently from the world it claims to be — the same
    // reasoning `assertBuildOutcomes` applies to an unknown refusal key.
    const keys = Object.keys(row);
    if (keys.length !== 2) {
      throw new Error(
        `Save is corrupt: world.guestOutcomes.departures[${index}] carries ${keys.length} key(s) (${keys.join(', ')}); a row is exactly a reason and a count`,
      );
    }
  });

  // The cross-field half, and the reason this runs at LOAD time and not only in the
  // tick: a save carrying a reservation on a room that is not in the same save would
  // otherwise load happily, report a healthy zero orphans, and be wrong. §6.1's
  // reservation leak is unreachable through the tick, so the only way one can enter the
  // world is from outside it — through here. Same functions the tick uses, so "a valid
  // guest store" has one definition.
  // Against the plot THIS SAVE carries rather than this build's default, for the reason the
  // entity store is checked against it (see above): a guest's position is only meaningful
  // against the coordinate space its own world was played on.
  assertGuestStoreInvariants(
    guests as unknown as GuestStore,
    entities as unknown as EntityStore,
    grid as unknown as GridBounds,
  );
  assertGuestOutcomes(guestOutcomes as unknown as GuestOutcomes, guests as unknown as GuestStore);

  // The per-need tally (G-012). Same function the tick calls at its own boundary, so "a
  // valid need tally" has one definition rather than two that drift. Checked AFTER the
  // guest outcomes, because its own law is stated against the departure count those
  // counters carry — a tally can only be judged against the guests it claims to describe.
  const needOutcomes = value['needOutcomes'];
  if (!Array.isArray(needOutcomes)) {
    throw new Error('Save is corrupt: world.needOutcomes is missing or not an array');
  }
  needOutcomes.forEach((row: unknown, index: number) => {
    if (!isRecord(row)) {
      throw new Error(`Save is corrupt: world.needOutcomes[${index}] is not an object`);
    }
    if (typeof row['needId'] !== 'string') {
      throw new Error(`Save is corrupt: world.needOutcomes[${index}].needId is not a string`);
    }
    for (const key of ['met', 'unmet'] as const) {
      if (typeof row[key] !== 'number') {
        throw new Error(`Save is corrupt: world.needOutcomes[${index}].${key} is not a number`);
      }
    }
  });
  assertNeedOutcomes(
    needOutcomes as unknown as readonly NeedOutcome[],
    departedGuests(guestOutcomes as unknown as GuestOutcomes),
  );

  // The review distribution (G-019). Same function the tick calls at its own boundary, and
  // checked after the guest outcomes for the reason the need tally is: its law is stated
  // against the departure count those counters carry.
  //
  // CONTENT-FREE, AND THAT IS WHY THE TABLE IS SPARSE. `assertWorldShape` runs at load,
  // where no content is in hand, so nothing here can ask whether a score lies inside the
  // scale this save was played under — the report asks that, where content exists. What CAN
  // be checked from the bytes alone is the shape: integer scores, strictly ascending, counts
  // of at least one, and no more reviews than there are departures. A fixed-length table
  // keyed by score would have had no content-free check available to it at all.
  const reviewOutcomes = value['reviewOutcomes'];
  if (!Array.isArray(reviewOutcomes)) {
    throw new Error('Save is corrupt: world.reviewOutcomes is missing or not an array');
  }
  reviewOutcomes.forEach((row: unknown, index: number) => {
    if (!isRecord(row)) {
      throw new Error(`Save is corrupt: world.reviewOutcomes[${index}] is not an object`);
    }
    for (const key of ['score', 'count'] as const) {
      if (typeof row[key] !== 'number') {
        throw new Error(`Save is corrupt: world.reviewOutcomes[${index}].${key} is missing or not a number`);
      }
    }
  });
  assertReviewOutcomes(
    reviewOutcomes as unknown as readonly ReviewOutcomeRow[],
    departedGuests(guestOutcomes as unknown as GuestOutcomes),
  );

  // The build counters (G-008). Same function the tick calls at its own boundary, so
  // "valid build outcomes" has one definition rather than two that drift. It checks every
  // known refusal reason is present AND that no unknown one is — an extra key would land
  // in the state hash (`worldToJson` is an identity cast) and make the restored world
  // hash differently from the world it claims to be.
  const buildOutcomes = value['buildOutcomes'];
  if (!isRecord(buildOutcomes)) {
    throw new Error('Save is corrupt: world.buildOutcomes is missing');
  }
  for (const key of ['built', 'demolished'] as const) {
    if (typeof buildOutcomes[key] !== 'number') {
      throw new Error(`Save is corrupt: world.buildOutcomes.${key} is missing or not a number`);
    }
  }
  if (!isRecord(buildOutcomes['refused'])) {
    throw new Error('Save is corrupt: world.buildOutcomes.refused is missing');
  }
  assertBuildOutcomes(buildOutcomes as unknown as BuildOutcomes);

  // The loan counters (G-011). Same function the tick calls at its own boundary, so
  // "valid loan outcomes" has one definition rather than two that drift. Note what is
  // NOT here: the outstanding debt. It is a fold over the ledger (`outstandingDebtOf`),
  // so there is no stored debt for a save to carry a wrong value of — I4's argument
  // applied past cash, and the reason this block is three fields rather than four.
  const loanOutcomes = value['loanOutcomes'];
  if (!isRecord(loanOutcomes)) {
    throw new Error('Save is corrupt: world.loanOutcomes is missing');
  }
  if (typeof loanOutcomes['drawn'] !== 'number') {
    throw new Error('Save is corrupt: world.loanOutcomes.drawn is missing or not a number');
  }
  if (!isRecord(loanOutcomes['refused'])) {
    throw new Error('Save is corrupt: world.loanOutcomes.refused is missing');
  }
  assertLoanOutcomes(loanOutcomes as unknown as LoanOutcomes);
}

export function serialise(world: World): string {
  const blob: SaveBlob = { schemaVersion: SAVE_SCHEMA_VERSION, world };
  return JSON.stringify(blob);
}

export function deserialise(json: string, schema: SaveSchema = SAVE_SCHEMA): World {
  // The chain is validated BEFORE it is used, on the real load path. It used to be
  // reachable only from a test, which meant the one function that could detect a broken
  // chain never ran in the place where a broken chain does damage. Loads are rare and
  // the chain is a frozen constant — this is a handful of integer comparisons, and it
  // is not in the tick.
  assertMigrationPathComplete(schema);

  // "This is not JSON" and "this is JSON but it is not a save" are different mistakes
  // with different fixes, and neither should surface as a raw parser grammar error —
  // the same reasoning as `parseContentJson` in packages/content, applied to the same
  // problem. A save interrupted mid-write is a likelier real corruption than most of
  // the shapes below, and it used to be the only one that escaped as a bare SyntaxError.
  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch (error) {
    throw new Error(`Save is corrupt: not valid JSON: ${describeError(error)}`);
  }
  if (!isRecord(parsed)) {
    throw new Error('Save is corrupt: top level is not an object');
  }

  const version = parsed['schemaVersion'];
  if (typeof version !== 'number' || !Number.isInteger(version)) {
    throw new Error('Save is corrupt: schemaVersion is missing or not an integer');
  }
  if (version < schema.minVersion) {
    throw new Error(`Save is v${version}; the oldest supported version is v${schema.minVersion}`);
  }
  if (version > schema.currentVersion) {
    throw new Error(
      `Save is v${version}, which is newer than this build (v${schema.currentVersion})`,
    );
  }

  const world = migrateSaveWorld(parsed['world'], version, schema);
  assertWorldShape(world);
  return world;
}
