// THE SCALING ARMS — ONE DEFINITION, TWO CONSUMERS, AND NO STOPWATCH (G-020c).
//
// The timing bounds that used to live in `needs.scaling.test.ts` and `scaling.test.ts` are
// now `pnpm check:scaling` (`tools/gates/scaling.mjs`). This file is what the gate's
// instrument and the surviving vitest assertions BOTH read, so the arms cannot drift apart:
// the shape G-018 removed from the bench's golden — a test declaring its own copies of the
// constants the gate runs — is exactly what two independent arm definitions would be.
//
// IT HOLDS NO CLOCK, DELIBERATELY. `tools/headless/src/needs.scaling.test.ts` ran its
// measurement in the `describe` BODY, so importing it started a stopwatch even for the
// assertions that never needed one. Anything that reads `process.hrtime` lives in
// `scaling-harness.ts`, which vitest never loads.
//
// WHY THE ROTATIONS ARE NAMED AND SEPARATE, AND IT IS A MEASURED PROPERTY RATHER THAN
// TIDINESS. Interleaved arms share one process's heap, GC and JIT, so ADDING OR REMOVING AN
// ARM CHANGES WHAT THE ARMS THAT REMAIN MEASURE. `sim-critic` measured 10.5% between the
// 4-arm and 3-arm need rotations at the median, alternated in one sitting, quiet,
// win32/12cpu. So a rotation is a workload: it gets a name, one process per invocation, and
// a reading taken under one rotation is never quoted against a reading taken under another.
//
// I1 does not reach here — this is `tools/headless`, which may use Node APIs. The
// simulation itself is untouched by this file.

import { bindContent } from '@hotelsim/sim';
import type { BoundContent, NeedTypeData, SimContent } from '@hotelsim/sim';
// THE GATE'S OWN CONSTANTS, IMPORTED RATHER THAN COPIED (G-027a, ADR-0021 MAJOR 1). See the
// note on `ROOMS` below for what the second copy cost.
import { ARRIVAL_EVERY_TICKS as GATE_ARRIVALS, ROOMS as GATE_ROOMS, SEED as GATE_SEED } from '../../gates/workload.mjs';

/** Six simulated hours — the length both scaling files have used since G-010. */
export const TICKS = 4_320;

/**
 * THE BENCH'S HOTEL — AND SINCE G-027a THAT IS TRUE OF THE CODE RATHER THAN OF A COMMENT.
 *
 * ============================================================================
 * THIS COMMENT WAS FALSE FOR ONE GOAL AND THE SENTENCE ABOVE IS THE ONE THAT WAS FALSE.
 * It read "the bench's hotel, so the criterion and the I5 gate describe the same building",
 * over three literals that were a SECOND COPY of `tools/gates/workload.mjs`. `bench.mjs` and
 * `measure.mjs` import that file; this one did not. So when ADR-0021 moved
 * `ARRIVAL_EVERY_TICKS` 32 -> 96 to restore the benchmark's calibrated occupancy of fifteen
 * concurrent guests, THIS file stayed at 32 and `check:scaling` went on measuring
 * FORTY-FIVE — against a campaign taken at fifteen.
 *
 * IT WAS INVISIBLE TO THE DRIFT GUARD, which is the part worth carrying forward.
 * `scaling.mjs` compares seed, ticks, samples and an arm fingerprint spelled in FLAGS
 * (`60r/32a`); no flag moved, because the flags are rendered from these very literals. A
 * guard fed by the thing it is guarding cannot see the thing move — G-018's
 * duplicated-constant defect, in the check meant to catch it.
 *
 * `tripwire.mjs` refused only because G-027a happened to move ITS literal. Had it not,
 * `check:tickcost` would have sailed through the same blind guard.
 * ============================================================================
 */
export const ROOMS = GATE_ROOMS;
export const ARRIVAL_EVERY_TICKS = GATE_ARRIVALS;
export const SEED = GATE_SEED;

/** The shipped default, and the hotel `sim:bench` measures. */
export const SPARSE_AMENITIES = 1;
/** How many of EACH amenity the dense arm seeds (G-013). */
export const DENSE_AMENITIES = 20;

/** An arm that is not a hotel at all — the anti-vacuity floor's comparison. */
export const IDLE_ARRIVALS = 999_999;

export type ArmSpec = {
  readonly name: string;
  readonly content: BoundContent;
  readonly rooms: number;
  readonly arrivals: number;
  readonly amenities: number;
};

/**
 * The shipped content cut down to the SMALLEST NEED VECTOR THIS MODEL CAN EXPRESS — the lodging
 * need and the lowest-id engagement need — with the room types and items that provide them.
 *
 * ============================================================================
 * IT WAS "THE LODGING NEED ALONE" UNTIL G-027b, AND THE NEEDS IT NOW KEEPS ARE FOUND RATHER
 * THAN CHOSEN. READ THIS BEFORE QUOTING A RATIO OFF THIS ARM.
 *
 * A stock decays and is refilled; the lodging need decays in AWAY time and nowhere else
 * (ADR-0017 §2), and away time is generated by ENGAGEMENT needs. So a table with a lodging need
 * and nothing else generates zero away-ticks, its lodging need can never become wanted, and
 * `bindContent` refuses it outright (`assertLodgingBecomesWanted`). Dropping the want line
 * instead does not help: a guest then forms every need already full with nothing recorded as
 * having served it, which `assertNeedVector` refuses on the first commit.
 *
 * IT IS WORSE THAN ONE EXTRA NEED, AND THE SECOND BOUND IS WHY. Rest must become wanted TWICE
 * inside a stay, so the away-time the engagement needs generate has to cover two crossings of
 * the want line: at the shipped rates one engagement need generates 180 away-ticks against the
 * 360 required, and TWO generate exactly 360. So the smallest legal control under the shipped
 * content is the lodging need plus TWO engagement needs — three of four.
 *
 * THE COUNT IS SEARCHED FOR, NOT WRITTEN DOWN. `smallestBindable` adds engagement needs in
 * ascending id order until `bindContent` accepts, so this file states no copy of the refusal's
 * arithmetic (which is the ADR-0021 duplicated-constant defect) and follows the content if it
 * is retuned.
 *
 * WHAT THE OLD ARM WAS FOR, so the loss is stated rather than absorbed: `one-need` against
 * `full-vector` is the NEED-VECTOR AXIS at fixed concurrent guests — same rooms, same arrivals,
 * same population, and only the length of each guest's vector differs. That axis survives and
 * its LEVER COLLAPSES from 4-against-1 to 4-against-3. **A ratio measured across that change is
 * not comparable with one measured before it, and one need of difference is a thin lever to
 * read a per-need cost off at all.** That is a finding about the gate rather than about this
 * file, and it is recorded here because this is where a reader meets it.
 *
 * THE ARM KEEPS THE NAME `one-need`, and that is deliberate: the string appears in
 * `tools/gates/scaling-bound.mjs` and `tools/gates/needs-history.mjs`, and a gate is not edited
 * to accommodate a fixture. The name is now short for "the smallest vector there is".
 * ============================================================================
 *
 * Reached through `role`, never through an id, for the reason `lodgingNeedOf` is: that is
 * what keeps the snake_case id that names it out of code (ADR-0003). The room types are
 * filtered too because `bindContent` refuses content in which a room provides a need that
 * does not exist, and refuses a need no room provides — so the two lists have to be cut
 * together or the arm would not bind at all.
 *
 * THE ITEM TABLE IS CUT WITH THEM (G-013), for the reason the room types are: an item that
 * provides a need this arm has removed makes `bindContent` refuse the arm outright. Their
 * `requires` links are untouched, so the rooms kept above stay furnishable and valid.
 *
 * AND THE FIT GOES WITH THE NEEDS (G-014a). A fit is a ranking of providers OF SOMETHING, so
 * an item that has just stopped providing anything may not keep one — `bindContent` refuses a
 * dial nothing can read. Dropping the key rather than zeroing it is the difference between
 * "this arm has no amenities" and "this arm ranks them all last".
 *
 * THE RULE IS THE SAME AT EVERY REVISION; WHAT DIFFERS IS THE CONTENT IT IS APPLIED TO.
 * `tools/headless/src/needs3-arm.ts` carries a copy of this function so it can be run inside an
 * extracted pre-G-013 tree, where `itemTypes` have no `provides` and no `fitBasisPoints` and
 * the filtering therefore removes nothing. That is the point: one filtering rule, each
 * revision's own tables (G-020c).
 */
export function lodgingOnly(bound: BoundContent): BoundContent {
  const all = bound.content.needTypes ?? [];
  const engagement = all.filter((entry) => entry.role !== 'lodging');
  // The table is normalised ascending by id, so which needs the first `n` are is a fact about
  // the content rather than about the order a designer typed them in (I2).
  let lastRefusal = 'none — the table has no engagement needs to cut';
  for (let take = 0; take < engagement.length; take += 1) {
    const keep = new Set(engagement.slice(0, take).map((entry) => entry.id));
    const candidate = all.filter((entry) => entry.role === 'lodging' || keep.has(entry.id));
    try {
      return cutTo(bound, candidate);
    } catch (error) {
      // Not enough away time yet for the lodging need to become wanted twice. Take one more —
      // and KEEP THE REASON, because the loop is a search and the last refusal is the only
      // evidence of why it ended. A bare `catch {}` here swallows a genuine bind error and
      // reports it as "a bigger table is needed", which is a wrong answer wearing a right one.
      lastRefusal = error instanceof Error ? error.message : String(error);
    }
  }
  // NOTHING SMALLER THAN THE WHOLE TABLE BINDS, AND THIS THROWS RATHER THAN RETURNING IT
  // (round 1). The comment here used to say this was "worth failing loudly on rather than
  // silently returning a control identical to the arm it is a control for" — and the next line
  // returned exactly that. An arm equal to its own control reports a ratio of 1.00 and looks
  // like a measurement.
  throw new Error(
    `lodgingOnly: no need table smaller than the full ${all.length}-need one binds, so the "one-need" arm would be ` +
      `identical to the full-vector arm it is the control for, and any ratio taken across the pair would be 1.00 by ` +
      `construction rather than by measurement. The last refusal was: ${lastRefusal}`,
  );
}

/** The content cut to `needTypes`, with everything that makes those needs reachable. */
function cutTo(bound: BoundContent, needTypes: readonly NeedTypeData[]): BoundContent {
  const kept = needTypes.map((entry) => entry.id);
  // A ROOM THAT PROVIDES NOTHING BUT HOSTS SOMETHING IS KEPT, and that clause is new at
  // G-027b. The engagement need this arm now has to carry may be provided by an ITEM, and an
  // item is only reachable through a room type that REQUIRES it — so filtering rooms on what
  // they provide alone would drop the host and make the need unreachable, which `bindContent`
  // refuses. The rule is "keep what makes a kept need reachable", which is what it always
  // meant when every kept need was room-provided.
  const hosts = (bound.content.itemTypes ?? [])
    .filter((itemType) => (itemType.provides ?? []).some((id) => kept.includes(id)))
    .map((itemType) => itemType.id);
  const roomTypes = bound.content.roomTypes
    .filter(
      (roomType) =>
        (roomType.provides ?? []).some((id) => kept.includes(id)) ||
        (roomType.requires ?? []).some((id) => hosts.includes(id)),
    )
    .map((roomType) => ({
      ...roomType,
      provides: (roomType.provides ?? []).filter((id) => kept.includes(id)),
    }));
  const itemTypes = (bound.content.itemTypes ?? []).map((itemType) => {
    const provides = (itemType.provides ?? []).filter((id) => kept.includes(id));
    // THE FIT GOES WITH THE NEEDS, AND ONLY WITH THE ONES THAT WENT (G-014a, narrowed at
    // G-027b). An item that has stopped providing anything may not keep a fit — `bindContent`
    // refuses a dial nothing can read — but an item that still serves a KEPT engagement need
    // must keep its own, because `bindContent` equally refuses a silent provider standing
    // beside declared ones. Dropping the key rather than zeroing it is still the difference
    // between "this arm has no amenities" and "this arm ranks them all last".
    if (provides.length > 0) return { ...itemType, provides };
    const { fitBasisPoints: _dropped, ...rest } = itemType;
    return { ...rest, provides };
  });
  // AND THE STAR LADDER GOES WITH THE ROOMS (G-051a). `bindContent` refuses a tier naming a
  // room type this content does not define — a tier nobody can satisfy is a ceiling nobody can
  // pass — so an arm that has just dropped the cafe may not keep a tier that wants one. It is
  // the same rule this function already applies to `provides` and to an item's fit: KEEP ONLY
  // WHAT THE CUT CONTENT CAN STILL NAME. The whole TIER goes rather than the clause, because
  // dropping a clause would silently change what that tier means; and nothing in the tick loop
  // reads a rating, so no measured quantity moves either way.
  const starTiers = (bound.content.starTiers ?? []).filter((tier) =>
    tier.requires.every((clause) => clause.roomTypeIds.every((id) => roomTypes.some((room) => room.id === id))),
  );
  return bindContent({ ...bound.content, roomTypes, needTypes, itemTypes, starTiers } satisfies SimContent);
}

const idleArm = (full: BoundContent): ArmSpec => ({
  name: 'idle',
  content: full,
  rooms: 0,
  arrivals: IDLE_ARRIVALS,
  amenities: SPARSE_AMENITIES,
});

/**
 * THE NEED ROTATION (G-016, G-013) — four arms.
 *
 * `one-need` against `full-vector` is the need-vector axis at FIXED concurrent guests: both
 * run the same 60-room hotel with the same arrival cadence, so the number of guests alive at
 * any moment is the same and only the vector each carries differs.
 *
 * `dense-providers` is `full-vector` with 20 of each amenity instead of one: same content,
 * same need count, same guest population, so `findFreeRoom`'s `exhausted` short-circuit stops
 * firing and the candidate lists are genuinely walked.
 */
export function needRotation(full: BoundContent): readonly ArmSpec[] {
  const oneNeed = lodgingOnly(full);
  return [
    idleArm(full),
    { name: 'one-need', content: oneNeed, rooms: ROOMS, arrivals: ARRIVAL_EVERY_TICKS, amenities: SPARSE_AMENITIES },
    { name: 'full-vector', content: full, rooms: ROOMS, arrivals: ARRIVAL_EVERY_TICKS, amenities: SPARSE_AMENITIES },
    { name: 'dense-providers', content: full, rooms: ROOMS, arrivals: ARRIVAL_EVERY_TICKS, amenities: DENSE_AMENITIES },
  ];
}

/**
 * THE THREE-ARM NEED ROTATION — the one that exists at BOTH revisions (G-020c).
 *
 * `dense-providers` cannot exist before G-013, because items were not providers and
 * `--amenities 20` seeds twenty copies of nothing that scores. So the cross-revision
 * measurement runs THIS rotation on both sides, and its readings are a different quantity
 * from the four-arm rotation's — see the header on rotations.
 */
export function needRotationOfThree(full: BoundContent): readonly ArmSpec[] {
  const oneNeed = lodgingOnly(full);
  return [
    idleArm(full),
    { name: 'one-need', content: oneNeed, rooms: ROOMS, arrivals: ARRIVAL_EVERY_TICKS, amenities: SPARSE_AMENITIES },
    { name: 'full-vector', content: full, rooms: ROOMS, arrivals: ARRIVAL_EVERY_TICKS, amenities: SPARSE_AMENITIES },
  ];
}

/**
 * THE ROOM ROTATION (G-010) — five arms, and the arrival rate scales with the room count.
 *
 * `PARKING.md` carries the correction that produced that rule: a scaling reading taken with
 * `--arrivals` held constant while rooms quadrupled measured 2.17x and was worthless, because
 * 96 of the 100 rooms sat empty all year and guest load — the actual cost driver — never
 * moved. Four times the rooms, four times the guests, identical occupancy in both arms.
 *
 * TWO PAIRS, BOTH ASSERTED. The saturated pair is the workload `PARKING.md` measured and the
 * one the free-room short-circuit targets; the bench-matched pair is the occupancy
 * `sim:bench` runs at. Measuring only the second would be choosing the workload that flatters
 * the fix.
 */
export function roomRotation(full: BoundContent): readonly ArmSpec[] {
  const arm = (name: string, rooms: number, arrivals: number): ArmSpec => ({
    name,
    content: full,
    rooms,
    arrivals,
    amenities: SPARSE_AMENITIES,
  });
  return [
    idleArm(full),
    arm('saturated-25', 25, 20),
    arm('saturated-100', 100, 5),
    arm('bench-25', 25, 60),
    arm('bench-100', 100, 15),
  ];
}

/**
 * WHICH PAIR OF ARMS IS WHICH AXIS. The pairing is a property of the WORKLOAD, so it lives
 * here beside the arms; the BOUND on each axis is a judgement and lives in
 * `tools/gates/scaling-bound.mjs`. `tools/gates/scaling.mjs` asserts the two sets of axis
 * names are equal in both directions, so an axis that is measured and not bounded — or
 * bounded and not measured — is a hard failure rather than a quietly missing assertion.
 */
export type RatioSpec = {
  readonly axis: string;
  readonly head: string;
  readonly base: string;
  /** Why the ratio must exceed 1: a bound alone is also satisfied by the arms swapping. */
  readonly because: string;
};

/** Arms that must cost materially more than `idle`, or the ratios above are ratios of
 *  overhead and prove nothing (ADR-0007's anti-vacuity floor). */
export type FloorSpec = { readonly arm: string };

/** A cost ordering that is not a bounded ratio — the two arms must be different workloads. */
export type OrderSpec = { readonly dearer: string; readonly cheaper: string; readonly because: string };

export const RATIOS: Readonly<Record<string, readonly RatioSpec[]>> = {
  needs: [
    {
      axis: 'needs',
      head: 'full-vector',
      base: 'one-need',
      because: 'the full vector must be the more expensive arm, or the arms are not what they claim',
    },
    {
      axis: 'density',
      head: 'dense-providers',
      base: 'full-vector',
      because: 'the dense hotel must cost more than the sparse one at the same need count',
    },
  ],
  needs3: [
    {
      axis: 'needs',
      head: 'full-vector',
      base: 'one-need',
      because: 'the full vector must be the more expensive arm, or the arms are not what they claim',
    },
  ],
  rooms: [
    {
      axis: 'rooms-saturated',
      head: 'saturated-100',
      base: 'saturated-25',
      because: 'four times the rooms and four times the guests must cost more, not less',
    },
    {
      axis: 'rooms-bench',
      head: 'bench-100',
      base: 'bench-25',
      because: 'four times the rooms and four times the guests must cost more, not less',
    },
  ],
} as const;

export const FLOORS: Readonly<Record<string, readonly FloorSpec[]>> = {
  needs: [{ arm: 'full-vector' }, { arm: 'one-need' }],
  needs3: [{ arm: 'full-vector' }, { arm: 'one-need' }],
  rooms: [{ arm: 'saturated-100' }, { arm: 'bench-100' }],
} as const;

export const ORDERS: Readonly<Record<string, readonly OrderSpec[]>> = {
  needs: [],
  needs3: [],
  rooms: [
    {
      dearer: 'saturated-100',
      cheaper: 'bench-100',
      because:
        'the saturated arm queues guests and the bench-matched arm does not, so the two ratios ' +
        'must not be one workload measured twice under two names',
    },
  ],
} as const;

/** The rotations the instrument can be asked for, by name. */
export const ROTATIONS = {
  needs: needRotation,
  needs3: needRotationOfThree,
  rooms: roomRotation,
} as const;

export type RotationName = keyof typeof ROTATIONS;

export const ROTATION_NAMES = Object.keys(ROTATIONS) as readonly RotationName[];

export const isRotationName = (name: string): name is RotationName =>
  Object.prototype.hasOwnProperty.call(ROTATIONS, name);
